spring:
  profiles:
    group:
      "local": "local,common"
      "dev":  "dev,common"
      "prod": "prod,common"

---

spring:
  application:
    name: classlink_api
  main:
    allow-circular-references: true
  config:
    activate:
      on-profile: "common"
  
mybatis:
  type-aliases-package: com.itsnowball.authentication.domain
  mapper-locations: classpath:mapper/**/*.xml

---

spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.171.101.31:3106/inshop?characterEncoding=UTF-8&serverTimezone=UTC
    username: deannn
    password: deannn123
    hikari:
      maximum-pool-size: 10

server: 
  port: 8001
  
---


spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.171.101.31:45336/classlink?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: classlink
    password: classlink!02$
    hikari:
      maximum-pool-size: 10
      
server: 
  port: 8001
  live: true
---


spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.171.101.31:45336/classlink?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: classlink
    password: classlink!02$
    hikari:
      maximum-pool-size: 10
logging:
  level: 
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: WARN

server: 
  port: 8301
  live: true
