// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CWQuestionBoxQuestionDetailRes.proto

package com.classlink.websocket.api.cw.domain.dto.proto;

public final class CWQuestionBoxQuestionDetailResProto {
  private CWQuestionBoxQuestionDetailResProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CWQuestionBoxQuestionDetailResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.CWQuestionBoxQuestionDetailRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
     * @return Whether the questionDetailData field is set.
     */
    boolean hasQuestionDetailData();
    /**
     * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
     * @return The questionDetailData.
     */
    com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail getQuestionDetailData();
    /**
     * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
     */
    com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder getQuestionDetailDataOrBuilder();
  }
  /**
   * Protobuf type {@code Classlink.CWQuestionBoxQuestionDetailRes}
   */
  public static final class CWQuestionBoxQuestionDetailRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.CWQuestionBoxQuestionDetailRes)
      CWQuestionBoxQuestionDetailResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CWQuestionBoxQuestionDetailRes.newBuilder() to construct.
    private CWQuestionBoxQuestionDetailRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CWQuestionBoxQuestionDetailRes() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CWQuestionBoxQuestionDetailRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.class, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.Builder.class);
    }

    public interface QuestionDetailOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 QuestionIdx = 1;</code>
       * @return The questionIdx.
       */
      int getQuestionIdx();

      /**
       * <code>string Title = 2;</code>
       * @return The title.
       */
      java.lang.String getTitle();
      /**
       * <code>string Title = 2;</code>
       * @return The bytes for title.
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <code>string Question = 3;</code>
       * @return The question.
       */
      java.lang.String getQuestion();
      /**
       * <code>string Question = 3;</code>
       * @return The bytes for question.
       */
      com.google.protobuf.ByteString
          getQuestionBytes();

      /**
       * <code>string TeacherName = 4;</code>
       * @return The teacherName.
       */
      java.lang.String getTeacherName();
      /**
       * <code>string TeacherName = 4;</code>
       * @return The bytes for teacherName.
       */
      com.google.protobuf.ByteString
          getTeacherNameBytes();

      /**
       * <code>string RegistDate = 5;</code>
       * @return The registDate.
       */
      java.lang.String getRegistDate();
      /**
       * <code>string RegistDate = 5;</code>
       * @return The bytes for registDate.
       */
      com.google.protobuf.ByteString
          getRegistDateBytes();

      /**
       * <pre>
       *repeated FileMetaInfo FileMetaInfoList = 7;
       * </pre>
       *
       * <code>int32 Status = 6;</code>
       * @return The status.
       */
      int getStatus();
    }
    /**
     * Protobuf type {@code Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail}
     */
    public static final class QuestionDetail extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail)
        QuestionDetailOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use QuestionDetail.newBuilder() to construct.
      private QuestionDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private QuestionDetail() {
        title_ = "";
        question_ = "";
        teacherName_ = "";
        registDate_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new QuestionDetail();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.class, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder.class);
      }

      public static final int QUESTIONIDX_FIELD_NUMBER = 1;
      private int questionIdx_;
      /**
       * <code>int32 QuestionIdx = 1;</code>
       * @return The questionIdx.
       */
      @java.lang.Override
      public int getQuestionIdx() {
        return questionIdx_;
      }

      public static final int TITLE_FIELD_NUMBER = 2;
      private volatile java.lang.Object title_;
      /**
       * <code>string Title = 2;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        }
      }
      /**
       * <code>string Title = 2;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int QUESTION_FIELD_NUMBER = 3;
      private volatile java.lang.Object question_;
      /**
       * <code>string Question = 3;</code>
       * @return The question.
       */
      @java.lang.Override
      public java.lang.String getQuestion() {
        java.lang.Object ref = question_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          question_ = s;
          return s;
        }
      }
      /**
       * <code>string Question = 3;</code>
       * @return The bytes for question.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getQuestionBytes() {
        java.lang.Object ref = question_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          question_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TEACHERNAME_FIELD_NUMBER = 4;
      private volatile java.lang.Object teacherName_;
      /**
       * <code>string TeacherName = 4;</code>
       * @return The teacherName.
       */
      @java.lang.Override
      public java.lang.String getTeacherName() {
        java.lang.Object ref = teacherName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          teacherName_ = s;
          return s;
        }
      }
      /**
       * <code>string TeacherName = 4;</code>
       * @return The bytes for teacherName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTeacherNameBytes() {
        java.lang.Object ref = teacherName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teacherName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int REGISTDATE_FIELD_NUMBER = 5;
      private volatile java.lang.Object registDate_;
      /**
       * <code>string RegistDate = 5;</code>
       * @return The registDate.
       */
      @java.lang.Override
      public java.lang.String getRegistDate() {
        java.lang.Object ref = registDate_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          registDate_ = s;
          return s;
        }
      }
      /**
       * <code>string RegistDate = 5;</code>
       * @return The bytes for registDate.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getRegistDateBytes() {
        java.lang.Object ref = registDate_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          registDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATUS_FIELD_NUMBER = 6;
      private int status_;
      /**
       * <pre>
       *repeated FileMetaInfo FileMetaInfoList = 7;
       * </pre>
       *
       * <code>int32 Status = 6;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (questionIdx_ != 0) {
          output.writeInt32(1, questionIdx_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(question_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, question_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(teacherName_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, teacherName_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registDate_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, registDate_);
        }
        if (status_ != 0) {
          output.writeInt32(6, status_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (questionIdx_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, questionIdx_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(question_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, question_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(teacherName_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, teacherName_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(registDate_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, registDate_);
        }
        if (status_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, status_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail)) {
          return super.equals(obj);
        }
        com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail other = (com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail) obj;

        if (getQuestionIdx()
            != other.getQuestionIdx()) return false;
        if (!getTitle()
            .equals(other.getTitle())) return false;
        if (!getQuestion()
            .equals(other.getQuestion())) return false;
        if (!getTeacherName()
            .equals(other.getTeacherName())) return false;
        if (!getRegistDate()
            .equals(other.getRegistDate())) return false;
        if (getStatus()
            != other.getStatus()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + QUESTIONIDX_FIELD_NUMBER;
        hash = (53 * hash) + getQuestionIdx();
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
        hash = (37 * hash) + QUESTION_FIELD_NUMBER;
        hash = (53 * hash) + getQuestion().hashCode();
        hash = (37 * hash) + TEACHERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getTeacherName().hashCode();
        hash = (37 * hash) + REGISTDATE_FIELD_NUMBER;
        hash = (53 * hash) + getRegistDate().hashCode();
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail)
          com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.class, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder.class);
        }

        // Construct using com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          questionIdx_ = 0;

          title_ = "";

          question_ = "";

          teacherName_ = "";

          registDate_ = "";

          status_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_descriptor;
        }

        @java.lang.Override
        public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail getDefaultInstanceForType() {
          return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.getDefaultInstance();
        }

        @java.lang.Override
        public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail build() {
          com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail buildPartial() {
          com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail result = new com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail(this);
          result.questionIdx_ = questionIdx_;
          result.title_ = title_;
          result.question_ = question_;
          result.teacherName_ = teacherName_;
          result.registDate_ = registDate_;
          result.status_ = status_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail) {
            return mergeFrom((com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail other) {
          if (other == com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.getDefaultInstance()) return this;
          if (other.getQuestionIdx() != 0) {
            setQuestionIdx(other.getQuestionIdx());
          }
          if (!other.getTitle().isEmpty()) {
            title_ = other.title_;
            onChanged();
          }
          if (!other.getQuestion().isEmpty()) {
            question_ = other.question_;
            onChanged();
          }
          if (!other.getTeacherName().isEmpty()) {
            teacherName_ = other.teacherName_;
            onChanged();
          }
          if (!other.getRegistDate().isEmpty()) {
            registDate_ = other.registDate_;
            onChanged();
          }
          if (other.getStatus() != 0) {
            setStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  questionIdx_ = input.readInt32();

                  break;
                } // case 8
                case 18: {
                  title_ = input.readStringRequireUtf8();

                  break;
                } // case 18
                case 26: {
                  question_ = input.readStringRequireUtf8();

                  break;
                } // case 26
                case 34: {
                  teacherName_ = input.readStringRequireUtf8();

                  break;
                } // case 34
                case 42: {
                  registDate_ = input.readStringRequireUtf8();

                  break;
                } // case 42
                case 48: {
                  status_ = input.readInt32();

                  break;
                } // case 48
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }

        private int questionIdx_ ;
        /**
         * <code>int32 QuestionIdx = 1;</code>
         * @return The questionIdx.
         */
        @java.lang.Override
        public int getQuestionIdx() {
          return questionIdx_;
        }
        /**
         * <code>int32 QuestionIdx = 1;</code>
         * @param value The questionIdx to set.
         * @return This builder for chaining.
         */
        public Builder setQuestionIdx(int value) {
          
          questionIdx_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 QuestionIdx = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearQuestionIdx() {
          
          questionIdx_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object title_ = "";
        /**
         * <code>string Title = 2;</code>
         * @return The title.
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string Title = 2;</code>
         * @return The bytes for title.
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string Title = 2;</code>
         * @param value The title to set.
         * @return This builder for chaining.
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string Title = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearTitle() {
          
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>string Title = 2;</code>
         * @param value The bytes for title to set.
         * @return This builder for chaining.
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          title_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object question_ = "";
        /**
         * <code>string Question = 3;</code>
         * @return The question.
         */
        public java.lang.String getQuestion() {
          java.lang.Object ref = question_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            question_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string Question = 3;</code>
         * @return The bytes for question.
         */
        public com.google.protobuf.ByteString
            getQuestionBytes() {
          java.lang.Object ref = question_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            question_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string Question = 3;</code>
         * @param value The question to set.
         * @return This builder for chaining.
         */
        public Builder setQuestion(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          question_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string Question = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearQuestion() {
          
          question_ = getDefaultInstance().getQuestion();
          onChanged();
          return this;
        }
        /**
         * <code>string Question = 3;</code>
         * @param value The bytes for question to set.
         * @return This builder for chaining.
         */
        public Builder setQuestionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          question_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object teacherName_ = "";
        /**
         * <code>string TeacherName = 4;</code>
         * @return The teacherName.
         */
        public java.lang.String getTeacherName() {
          java.lang.Object ref = teacherName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            teacherName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string TeacherName = 4;</code>
         * @return The bytes for teacherName.
         */
        public com.google.protobuf.ByteString
            getTeacherNameBytes() {
          java.lang.Object ref = teacherName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            teacherName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string TeacherName = 4;</code>
         * @param value The teacherName to set.
         * @return This builder for chaining.
         */
        public Builder setTeacherName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          teacherName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string TeacherName = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearTeacherName() {
          
          teacherName_ = getDefaultInstance().getTeacherName();
          onChanged();
          return this;
        }
        /**
         * <code>string TeacherName = 4;</code>
         * @param value The bytes for teacherName to set.
         * @return This builder for chaining.
         */
        public Builder setTeacherNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          teacherName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object registDate_ = "";
        /**
         * <code>string RegistDate = 5;</code>
         * @return The registDate.
         */
        public java.lang.String getRegistDate() {
          java.lang.Object ref = registDate_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            registDate_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string RegistDate = 5;</code>
         * @return The bytes for registDate.
         */
        public com.google.protobuf.ByteString
            getRegistDateBytes() {
          java.lang.Object ref = registDate_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            registDate_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string RegistDate = 5;</code>
         * @param value The registDate to set.
         * @return This builder for chaining.
         */
        public Builder setRegistDate(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          registDate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string RegistDate = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearRegistDate() {
          
          registDate_ = getDefaultInstance().getRegistDate();
          onChanged();
          return this;
        }
        /**
         * <code>string RegistDate = 5;</code>
         * @param value The bytes for registDate to set.
         * @return This builder for chaining.
         */
        public Builder setRegistDateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          registDate_ = value;
          onChanged();
          return this;
        }

        private int status_ ;
        /**
         * <pre>
         *repeated FileMetaInfo FileMetaInfoList = 7;
         * </pre>
         *
         * <code>int32 Status = 6;</code>
         * @return The status.
         */
        @java.lang.Override
        public int getStatus() {
          return status_;
        }
        /**
         * <pre>
         *repeated FileMetaInfo FileMetaInfoList = 7;
         * </pre>
         *
         * <code>int32 Status = 6;</code>
         * @param value The status to set.
         * @return This builder for chaining.
         */
        public Builder setStatus(int value) {
          
          status_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *repeated FileMetaInfo FileMetaInfoList = 7;
         * </pre>
         *
         * <code>int32 Status = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearStatus() {
          
          status_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail)
      }

      // @@protoc_insertion_point(class_scope:Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail)
      private static final com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail();
      }

      public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<QuestionDetail>
          PARSER = new com.google.protobuf.AbstractParser<QuestionDetail>() {
        @java.lang.Override
        public QuestionDetail parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<QuestionDetail> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<QuestionDetail> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int QUESTIONDETAILDATA_FIELD_NUMBER = 1;
    private com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail questionDetailData_;
    /**
     * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
     * @return Whether the questionDetailData field is set.
     */
    @java.lang.Override
    public boolean hasQuestionDetailData() {
      return questionDetailData_ != null;
    }
    /**
     * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
     * @return The questionDetailData.
     */
    @java.lang.Override
    public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail getQuestionDetailData() {
      return questionDetailData_ == null ? com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.getDefaultInstance() : questionDetailData_;
    }
    /**
     * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
     */
    @java.lang.Override
    public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder getQuestionDetailDataOrBuilder() {
      return getQuestionDetailData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (questionDetailData_ != null) {
        output.writeMessage(1, getQuestionDetailData());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (questionDetailData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getQuestionDetailData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes)) {
        return super.equals(obj);
      }
      com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes other = (com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes) obj;

      if (hasQuestionDetailData() != other.hasQuestionDetailData()) return false;
      if (hasQuestionDetailData()) {
        if (!getQuestionDetailData()
            .equals(other.getQuestionDetailData())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasQuestionDetailData()) {
        hash = (37 * hash) + QUESTIONDETAILDATA_FIELD_NUMBER;
        hash = (53 * hash) + getQuestionDetailData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.CWQuestionBoxQuestionDetailRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.CWQuestionBoxQuestionDetailRes)
        com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.class, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.Builder.class);
      }

      // Construct using com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (questionDetailDataBuilder_ == null) {
          questionDetailData_ = null;
        } else {
          questionDetailData_ = null;
          questionDetailDataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor;
      }

      @java.lang.Override
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes getDefaultInstanceForType() {
        return com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes build() {
        com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes buildPartial() {
        com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes result = new com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes(this);
        if (questionDetailDataBuilder_ == null) {
          result.questionDetailData_ = questionDetailData_;
        } else {
          result.questionDetailData_ = questionDetailDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes) {
          return mergeFrom((com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes other) {
        if (other == com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.getDefaultInstance()) return this;
        if (other.hasQuestionDetailData()) {
          mergeQuestionDetailData(other.getQuestionDetailData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getQuestionDetailDataFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail questionDetailData_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder> questionDetailDataBuilder_;
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       * @return Whether the questionDetailData field is set.
       */
      public boolean hasQuestionDetailData() {
        return questionDetailDataBuilder_ != null || questionDetailData_ != null;
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       * @return The questionDetailData.
       */
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail getQuestionDetailData() {
        if (questionDetailDataBuilder_ == null) {
          return questionDetailData_ == null ? com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.getDefaultInstance() : questionDetailData_;
        } else {
          return questionDetailDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      public Builder setQuestionDetailData(com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail value) {
        if (questionDetailDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          questionDetailData_ = value;
          onChanged();
        } else {
          questionDetailDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      public Builder setQuestionDetailData(
          com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder builderForValue) {
        if (questionDetailDataBuilder_ == null) {
          questionDetailData_ = builderForValue.build();
          onChanged();
        } else {
          questionDetailDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      public Builder mergeQuestionDetailData(com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail value) {
        if (questionDetailDataBuilder_ == null) {
          if (questionDetailData_ != null) {
            questionDetailData_ =
              com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.newBuilder(questionDetailData_).mergeFrom(value).buildPartial();
          } else {
            questionDetailData_ = value;
          }
          onChanged();
        } else {
          questionDetailDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      public Builder clearQuestionDetailData() {
        if (questionDetailDataBuilder_ == null) {
          questionDetailData_ = null;
          onChanged();
        } else {
          questionDetailData_ = null;
          questionDetailDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder getQuestionDetailDataBuilder() {
        
        onChanged();
        return getQuestionDetailDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder getQuestionDetailDataOrBuilder() {
        if (questionDetailDataBuilder_ != null) {
          return questionDetailDataBuilder_.getMessageOrBuilder();
        } else {
          return questionDetailData_ == null ?
              com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.getDefaultInstance() : questionDetailData_;
        }
      }
      /**
       * <code>.Classlink.CWQuestionBoxQuestionDetailRes.QuestionDetail QuestionDetailData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder> 
          getQuestionDetailDataFieldBuilder() {
        if (questionDetailDataBuilder_ == null) {
          questionDetailDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetail.Builder, com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes.QuestionDetailOrBuilder>(
                  getQuestionDetailData(),
                  getParentForChildren(),
                  isClean());
          questionDetailData_ = null;
        }
        return questionDetailDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.CWQuestionBoxQuestionDetailRes)
    }

    // @@protoc_insertion_point(class_scope:Classlink.CWQuestionBoxQuestionDetailRes)
    private static final com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes();
    }

    public static com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CWQuestionBoxQuestionDetailRes>
        PARSER = new com.google.protobuf.AbstractParser<CWQuestionBoxQuestionDetailRes>() {
      @java.lang.Override
      public CWQuestionBoxQuestionDetailRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CWQuestionBoxQuestionDetailRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CWQuestionBoxQuestionDetailRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classlink.websocket.api.cw.domain.dto.proto.CWQuestionBoxQuestionDetailResProto.CWQuestionBoxQuestionDetailRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_CWQuestionBoxQuestionDetailRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$CWQuestionBoxQuestionDetailRes.proto\022\t" +
      "Classlink\"\367\001\n\036CWQuestionBoxQuestionDetai" +
      "lRes\022T\n\022QuestionDetailData\030\001 \001(\01328.Class" +
      "link.CWQuestionBoxQuestionDetailRes.Ques" +
      "tionDetail\032\177\n\016QuestionDetail\022\023\n\013Question" +
      "Idx\030\001 \001(\005\022\r\n\005Title\030\002 \001(\t\022\020\n\010Question\030\003 \001" +
      "(\t\022\023\n\013TeacherName\030\004 \001(\t\022\022\n\nRegistDate\030\005 " +
      "\001(\t\022\016\n\006Status\030\006 \001(\005BV\n/com.classlink.web" +
      "socket.api.cw.domain.dto.protoB#CWQuesti" +
      "onBoxQuestionDetailResProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_CWQuestionBoxQuestionDetailRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor,
        new java.lang.String[] { "QuestionDetailData", });
    internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_descriptor =
      internal_static_Classlink_CWQuestionBoxQuestionDetailRes_descriptor.getNestedTypes().get(0);
    internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_CWQuestionBoxQuestionDetailRes_QuestionDetail_descriptor,
        new java.lang.String[] { "QuestionIdx", "Title", "Question", "TeacherName", "RegistDate", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
