// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SysWorldInterObjSetCurriculumInitRes.proto

package com.classlink.websocket.api.system.domain.dto.proto;

public final class SysWorldInterObjSetCurriculumInitResProto {
  private SysWorldInterObjSetCurriculumInitResProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SysWorldInterObjSetCurriculumInitResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.SysWorldInterObjSetCurriculumInitRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    java.util.List<SysWorldInterObjSetCurriculumInitRes.InteractionObject>
        getInteractionObjectListList();
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    SysWorldInterObjSetCurriculumInitRes.InteractionObject getInteractionObjectList(int index);
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    int getInteractionObjectListCount();
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    java.util.List<? extends SysWorldInterObjSetCurriculumInitRes.InteractionObjectOrBuilder>
        getInteractionObjectListOrBuilderList();
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    SysWorldInterObjSetCurriculumInitRes.InteractionObjectOrBuilder getInteractionObjectListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Classlink.SysWorldInterObjSetCurriculumInitRes}
   */
  public static final class SysWorldInterObjSetCurriculumInitRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.SysWorldInterObjSetCurriculumInitRes)
      SysWorldInterObjSetCurriculumInitResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SysWorldInterObjSetCurriculumInitRes.newBuilder() to construct.
    private SysWorldInterObjSetCurriculumInitRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SysWorldInterObjSetCurriculumInitRes() {
      interactionObjectList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SysWorldInterObjSetCurriculumInitRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SysWorldInterObjSetCurriculumInitRes.class, Builder.class);
    }

    public interface InteractionObjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       *자료실과 연결필요
       * </pre>
       *
       * <code>int32 Idx = 1;</code>
       * @return The idx.
       */
      int getIdx();

      /**
       * <pre>
       *오브젝트코드값인지 오브젝트 ID인지 확인필요
       * </pre>
       *
       * <code>string Code = 2;</code>
       * @return The code.
       */
      String getCode();
      /**
       * <pre>
       *오브젝트코드값인지 오브젝트 ID인지 확인필요
       * </pre>
       *
       * <code>string Code = 2;</code>
       * @return The bytes for code.
       */
      com.google.protobuf.ByteString
          getCodeBytes();

      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataTableType = 3;</code>
       * @return The dataTableType.
       */
      String getDataTableType();
      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataTableType = 3;</code>
       * @return The bytes for dataTableType.
       */
      com.google.protobuf.ByteString
          getDataTableTypeBytes();

      /**
       * <code>int32 DataIdx = 4;</code>
       * @return The dataIdx.
       */
      int getDataIdx();

      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataType = 5;</code>
       * @return The dataType.
       */
      String getDataType();
      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataType = 5;</code>
       * @return The bytes for dataType.
       */
      com.google.protobuf.ByteString
          getDataTypeBytes();

      /**
       * <pre>
       *자료실과 연결필요
       * </pre>
       *
       * <code>string Data = 6;</code>
       * @return The data.
       */
      String getData();
      /**
       * <pre>
       *자료실과 연결필요
       * </pre>
       *
       * <code>string Data = 6;</code>
       * @return The bytes for data.
       */
      com.google.protobuf.ByteString
          getDataBytes();
    }
    /**
     * Protobuf type {@code Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject}
     */
    public static final class InteractionObject extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject)
        InteractionObjectOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use InteractionObject.newBuilder() to construct.
      private InteractionObject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private InteractionObject() {
        code_ = "";
        dataTableType_ = "";
        dataType_ = "";
        data_ = "";
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new InteractionObject();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InteractionObject.class, Builder.class);
      }

      public static final int IDX_FIELD_NUMBER = 1;
      private int idx_;
      /**
       * <pre>
       *자료실과 연결필요
       * </pre>
       *
       * <code>int32 Idx = 1;</code>
       * @return The idx.
       */
      @Override
      public int getIdx() {
        return idx_;
      }

      public static final int CODE_FIELD_NUMBER = 2;
      private volatile Object code_;
      /**
       * <pre>
       *오브젝트코드값인지 오브젝트 ID인지 확인필요
       * </pre>
       *
       * <code>string Code = 2;</code>
       * @return The code.
       */
      @Override
      public String getCode() {
        Object ref = code_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          code_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *오브젝트코드값인지 오브젝트 ID인지 확인필요
       * </pre>
       *
       * <code>string Code = 2;</code>
       * @return The bytes for code.
       */
      @Override
      public com.google.protobuf.ByteString
          getCodeBytes() {
        Object ref = code_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          code_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATATABLETYPE_FIELD_NUMBER = 3;
      private volatile Object dataTableType_;
      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataTableType = 3;</code>
       * @return The dataTableType.
       */
      @Override
      public String getDataTableType() {
        Object ref = dataTableType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataTableType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataTableType = 3;</code>
       * @return The bytes for dataTableType.
       */
      @Override
      public com.google.protobuf.ByteString
          getDataTableTypeBytes() {
        Object ref = dataTableType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataTableType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATAIDX_FIELD_NUMBER = 4;
      private int dataIdx_;
      /**
       * <code>int32 DataIdx = 4;</code>
       * @return The dataIdx.
       */
      @Override
      public int getDataIdx() {
        return dataIdx_;
      }

      public static final int DATATYPE_FIELD_NUMBER = 5;
      private volatile Object dataType_;
      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataType = 5;</code>
       * @return The dataType.
       */
      @Override
      public String getDataType() {
        Object ref = dataType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataType_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
       * </pre>
       *
       * <code>string DataType = 5;</code>
       * @return The bytes for dataType.
       */
      @Override
      public com.google.protobuf.ByteString
          getDataTypeBytes() {
        Object ref = dataType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int DATA_FIELD_NUMBER = 6;
      private volatile Object data_;
      /**
       * <pre>
       *자료실과 연결필요
       * </pre>
       *
       * <code>string Data = 6;</code>
       * @return The data.
       */
      @Override
      public String getData() {
        Object ref = data_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        }
      }
      /**
       * <pre>
       *자료실과 연결필요
       * </pre>
       *
       * <code>string Data = 6;</code>
       * @return The bytes for data.
       */
      @Override
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (idx_ != 0) {
          output.writeInt32(1, idx_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, code_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataTableType_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataTableType_);
        }
        if (dataIdx_ != 0) {
          output.writeInt32(4, dataIdx_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataType_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dataType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 6, data_);
        }
        getUnknownFields().writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (idx_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, idx_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(code_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, code_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataTableType_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataTableType_);
        }
        if (dataIdx_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, dataIdx_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataType_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dataType_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, data_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof InteractionObject)) {
          return super.equals(obj);
        }
        InteractionObject other = (InteractionObject) obj;

        if (getIdx()
            != other.getIdx()) return false;
        if (!getCode()
            .equals(other.getCode())) return false;
        if (!getDataTableType()
            .equals(other.getDataTableType())) return false;
        if (getDataIdx()
            != other.getDataIdx()) return false;
        if (!getDataType()
            .equals(other.getDataType())) return false;
        if (!getData()
            .equals(other.getData())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + IDX_FIELD_NUMBER;
        hash = (53 * hash) + getIdx();
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCode().hashCode();
        hash = (37 * hash) + DATATABLETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getDataTableType().hashCode();
        hash = (37 * hash) + DATAIDX_FIELD_NUMBER;
        hash = (53 * hash) + getDataIdx();
        hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
        hash = (53 * hash) + getDataType().hashCode();
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static InteractionObject parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static InteractionObject parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static InteractionObject parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static InteractionObject parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static InteractionObject parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static InteractionObject parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static InteractionObject parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static InteractionObject parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static InteractionObject parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static InteractionObject parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static InteractionObject parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static InteractionObject parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(InteractionObject prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject)
          InteractionObjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  InteractionObject.class, Builder.class);
        }

        // Construct using com.classlink.websocket.api.system.domain.dto.proto.SysWorldInterObjSetCurriculumInitResProto.SysWorldInterObjSetCurriculumInitRes.InteractionObject.newBuilder()
        private Builder() {

        }

        private Builder(
            BuilderParent parent) {
          super(parent);

        }
        @Override
        public Builder clear() {
          super.clear();
          idx_ = 0;

          code_ = "";

          dataTableType_ = "";

          dataIdx_ = 0;

          dataType_ = "";

          data_ = "";

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_descriptor;
        }

        @Override
        public InteractionObject getDefaultInstanceForType() {
          return InteractionObject.getDefaultInstance();
        }

        @Override
        public InteractionObject build() {
          InteractionObject result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public InteractionObject buildPartial() {
          InteractionObject result = new InteractionObject(this);
          result.idx_ = idx_;
          result.code_ = code_;
          result.dataTableType_ = dataTableType_;
          result.dataIdx_ = dataIdx_;
          result.dataType_ = dataType_;
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof InteractionObject) {
            return mergeFrom((InteractionObject)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(InteractionObject other) {
          if (other == InteractionObject.getDefaultInstance()) return this;
          if (other.getIdx() != 0) {
            setIdx(other.getIdx());
          }
          if (!other.getCode().isEmpty()) {
            code_ = other.code_;
            onChanged();
          }
          if (!other.getDataTableType().isEmpty()) {
            dataTableType_ = other.dataTableType_;
            onChanged();
          }
          if (other.getDataIdx() != 0) {
            setDataIdx(other.getDataIdx());
          }
          if (!other.getDataType().isEmpty()) {
            dataType_ = other.dataType_;
            onChanged();
          }
          if (!other.getData().isEmpty()) {
            data_ = other.data_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  idx_ = input.readInt32();

                  break;
                } // case 8
                case 18: {
                  code_ = input.readStringRequireUtf8();

                  break;
                } // case 18
                case 26: {
                  dataTableType_ = input.readStringRequireUtf8();

                  break;
                } // case 26
                case 32: {
                  dataIdx_ = input.readInt32();

                  break;
                } // case 32
                case 42: {
                  dataType_ = input.readStringRequireUtf8();

                  break;
                } // case 42
                case 50: {
                  data_ = input.readStringRequireUtf8();

                  break;
                } // case 50
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }

        private int idx_ ;
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>int32 Idx = 1;</code>
         * @return The idx.
         */
        @Override
        public int getIdx() {
          return idx_;
        }
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>int32 Idx = 1;</code>
         * @param value The idx to set.
         * @return This builder for chaining.
         */
        public Builder setIdx(int value) {
          
          idx_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>int32 Idx = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearIdx() {
          
          idx_ = 0;
          onChanged();
          return this;
        }

        private Object code_ = "";
        /**
         * <pre>
         *오브젝트코드값인지 오브젝트 ID인지 확인필요
         * </pre>
         *
         * <code>string Code = 2;</code>
         * @return The code.
         */
        public String getCode() {
          Object ref = code_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            code_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *오브젝트코드값인지 오브젝트 ID인지 확인필요
         * </pre>
         *
         * <code>string Code = 2;</code>
         * @return The bytes for code.
         */
        public com.google.protobuf.ByteString
            getCodeBytes() {
          Object ref = code_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            code_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *오브젝트코드값인지 오브젝트 ID인지 확인필요
         * </pre>
         *
         * <code>string Code = 2;</code>
         * @param value The code to set.
         * @return This builder for chaining.
         */
        public Builder setCode(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          code_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *오브젝트코드값인지 오브젝트 ID인지 확인필요
         * </pre>
         *
         * <code>string Code = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearCode() {
          
          code_ = getDefaultInstance().getCode();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *오브젝트코드값인지 오브젝트 ID인지 확인필요
         * </pre>
         *
         * <code>string Code = 2;</code>
         * @param value The bytes for code to set.
         * @return This builder for chaining.
         */
        public Builder setCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          code_ = value;
          onChanged();
          return this;
        }

        private Object dataTableType_ = "";
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataTableType = 3;</code>
         * @return The dataTableType.
         */
        public String getDataTableType() {
          Object ref = dataTableType_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            dataTableType_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataTableType = 3;</code>
         * @return The bytes for dataTableType.
         */
        public com.google.protobuf.ByteString
            getDataTableTypeBytes() {
          Object ref = dataTableType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            dataTableType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataTableType = 3;</code>
         * @param value The dataTableType to set.
         * @return This builder for chaining.
         */
        public Builder setDataTableType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          dataTableType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataTableType = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearDataTableType() {
          
          dataTableType_ = getDefaultInstance().getDataTableType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataTableType = 3;</code>
         * @param value The bytes for dataTableType to set.
         * @return This builder for chaining.
         */
        public Builder setDataTableTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          dataTableType_ = value;
          onChanged();
          return this;
        }

        private int dataIdx_ ;
        /**
         * <code>int32 DataIdx = 4;</code>
         * @return The dataIdx.
         */
        @Override
        public int getDataIdx() {
          return dataIdx_;
        }
        /**
         * <code>int32 DataIdx = 4;</code>
         * @param value The dataIdx to set.
         * @return This builder for chaining.
         */
        public Builder setDataIdx(int value) {
          
          dataIdx_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 DataIdx = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearDataIdx() {
          
          dataIdx_ = 0;
          onChanged();
          return this;
        }

        private Object dataType_ = "";
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataType = 5;</code>
         * @return The dataType.
         */
        public String getDataType() {
          Object ref = dataType_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            dataType_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataType = 5;</code>
         * @return The bytes for dataType.
         */
        public com.google.protobuf.ByteString
            getDataTypeBytes() {
          Object ref = dataType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            dataType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataType = 5;</code>
         * @param value The dataType to set.
         * @return This builder for chaining.
         */
        public Builder setDataType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          dataType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataType = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearDataType() {
          
          dataType_ = getDefaultInstance().getDataType();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요 &amp; int가아닌 string 값이 되어야함
         * </pre>
         *
         * <code>string DataType = 5;</code>
         * @param value The bytes for dataType to set.
         * @return This builder for chaining.
         */
        public Builder setDataTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          dataType_ = value;
          onChanged();
          return this;
        }

        private Object data_ = "";
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>string Data = 6;</code>
         * @return The data.
         */
        public String getData() {
          Object ref = data_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            data_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>string Data = 6;</code>
         * @return The bytes for data.
         */
        public com.google.protobuf.ByteString
            getDataBytes() {
          Object ref = data_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            data_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>string Data = 6;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>string Data = 6;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        /**
         * <pre>
         *자료실과 연결필요
         * </pre>
         *
         * <code>string Data = 6;</code>
         * @param value The bytes for data to set.
         * @return This builder for chaining.
         */
        public Builder setDataBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          data_ = value;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject)
      }

      // @@protoc_insertion_point(class_scope:Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject)
      private static final InteractionObject DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new InteractionObject();
      }

      public static InteractionObject getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<InteractionObject>
          PARSER = new com.google.protobuf.AbstractParser<InteractionObject>() {
        @Override
        public InteractionObject parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<InteractionObject> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<InteractionObject> getParserForType() {
        return PARSER;
      }

      @Override
      public InteractionObject getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int INTERACTIONOBJECTLIST_FIELD_NUMBER = 1;
    private java.util.List<InteractionObject> interactionObjectList_;
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    @Override
    public java.util.List<InteractionObject> getInteractionObjectListList() {
      return interactionObjectList_;
    }
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    @Override
    public java.util.List<? extends InteractionObjectOrBuilder>
        getInteractionObjectListOrBuilderList() {
      return interactionObjectList_;
    }
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    @Override
    public int getInteractionObjectListCount() {
      return interactionObjectList_.size();
    }
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    @Override
    public InteractionObject getInteractionObjectList(int index) {
      return interactionObjectList_.get(index);
    }
    /**
     * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
     */
    @Override
    public InteractionObjectOrBuilder getInteractionObjectListOrBuilder(
        int index) {
      return interactionObjectList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < interactionObjectList_.size(); i++) {
        output.writeMessage(1, interactionObjectList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < interactionObjectList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, interactionObjectList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SysWorldInterObjSetCurriculumInitRes)) {
        return super.equals(obj);
      }
      SysWorldInterObjSetCurriculumInitRes other = (SysWorldInterObjSetCurriculumInitRes) obj;

      if (!getInteractionObjectListList()
          .equals(other.getInteractionObjectListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInteractionObjectListCount() > 0) {
        hash = (37 * hash) + INTERACTIONOBJECTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getInteractionObjectListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SysWorldInterObjSetCurriculumInitRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SysWorldInterObjSetCurriculumInitRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.SysWorldInterObjSetCurriculumInitRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.SysWorldInterObjSetCurriculumInitRes)
        SysWorldInterObjSetCurriculumInitResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SysWorldInterObjSetCurriculumInitRes.class, Builder.class);
      }

      // Construct using com.classlink.websocket.api.system.domain.dto.proto.SysWorldInterObjSetCurriculumInitResProto.SysWorldInterObjSetCurriculumInitRes.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        if (interactionObjectListBuilder_ == null) {
          interactionObjectList_ = java.util.Collections.emptyList();
        } else {
          interactionObjectList_ = null;
          interactionObjectListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SysWorldInterObjSetCurriculumInitResProto.internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor;
      }

      @Override
      public SysWorldInterObjSetCurriculumInitRes getDefaultInstanceForType() {
        return SysWorldInterObjSetCurriculumInitRes.getDefaultInstance();
      }

      @Override
      public SysWorldInterObjSetCurriculumInitRes build() {
        SysWorldInterObjSetCurriculumInitRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SysWorldInterObjSetCurriculumInitRes buildPartial() {
        SysWorldInterObjSetCurriculumInitRes result = new SysWorldInterObjSetCurriculumInitRes(this);
        int from_bitField0_ = bitField0_;
        if (interactionObjectListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            interactionObjectList_ = java.util.Collections.unmodifiableList(interactionObjectList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.interactionObjectList_ = interactionObjectList_;
        } else {
          result.interactionObjectList_ = interactionObjectListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SysWorldInterObjSetCurriculumInitRes) {
          return mergeFrom((SysWorldInterObjSetCurriculumInitRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SysWorldInterObjSetCurriculumInitRes other) {
        if (other == SysWorldInterObjSetCurriculumInitRes.getDefaultInstance()) return this;
        if (interactionObjectListBuilder_ == null) {
          if (!other.interactionObjectList_.isEmpty()) {
            if (interactionObjectList_.isEmpty()) {
              interactionObjectList_ = other.interactionObjectList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInteractionObjectListIsMutable();
              interactionObjectList_.addAll(other.interactionObjectList_);
            }
            onChanged();
          }
        } else {
          if (!other.interactionObjectList_.isEmpty()) {
            if (interactionObjectListBuilder_.isEmpty()) {
              interactionObjectListBuilder_.dispose();
              interactionObjectListBuilder_ = null;
              interactionObjectList_ = other.interactionObjectList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              interactionObjectListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInteractionObjectListFieldBuilder() : null;
            } else {
              interactionObjectListBuilder_.addAllMessages(other.interactionObjectList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                InteractionObject m =
                    input.readMessage(
                        InteractionObject.parser(),
                        extensionRegistry);
                if (interactionObjectListBuilder_ == null) {
                  ensureInteractionObjectListIsMutable();
                  interactionObjectList_.add(m);
                } else {
                  interactionObjectListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<InteractionObject> interactionObjectList_ =
        java.util.Collections.emptyList();
      private void ensureInteractionObjectListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          interactionObjectList_ = new java.util.ArrayList<InteractionObject>(interactionObjectList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          InteractionObject, InteractionObject.Builder, InteractionObjectOrBuilder> interactionObjectListBuilder_;

      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public java.util.List<InteractionObject> getInteractionObjectListList() {
        if (interactionObjectListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(interactionObjectList_);
        } else {
          return interactionObjectListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public int getInteractionObjectListCount() {
        if (interactionObjectListBuilder_ == null) {
          return interactionObjectList_.size();
        } else {
          return interactionObjectListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public InteractionObject getInteractionObjectList(int index) {
        if (interactionObjectListBuilder_ == null) {
          return interactionObjectList_.get(index);
        } else {
          return interactionObjectListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder setInteractionObjectList(
          int index, InteractionObject value) {
        if (interactionObjectListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.set(index, value);
          onChanged();
        } else {
          interactionObjectListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder setInteractionObjectList(
          int index, InteractionObject.Builder builderForValue) {
        if (interactionObjectListBuilder_ == null) {
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.set(index, builderForValue.build());
          onChanged();
        } else {
          interactionObjectListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder addInteractionObjectList(InteractionObject value) {
        if (interactionObjectListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.add(value);
          onChanged();
        } else {
          interactionObjectListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder addInteractionObjectList(
          int index, InteractionObject value) {
        if (interactionObjectListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.add(index, value);
          onChanged();
        } else {
          interactionObjectListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder addInteractionObjectList(
          InteractionObject.Builder builderForValue) {
        if (interactionObjectListBuilder_ == null) {
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.add(builderForValue.build());
          onChanged();
        } else {
          interactionObjectListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder addInteractionObjectList(
          int index, InteractionObject.Builder builderForValue) {
        if (interactionObjectListBuilder_ == null) {
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.add(index, builderForValue.build());
          onChanged();
        } else {
          interactionObjectListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder addAllInteractionObjectList(
          Iterable<? extends InteractionObject> values) {
        if (interactionObjectListBuilder_ == null) {
          ensureInteractionObjectListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, interactionObjectList_);
          onChanged();
        } else {
          interactionObjectListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder clearInteractionObjectList() {
        if (interactionObjectListBuilder_ == null) {
          interactionObjectList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          interactionObjectListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public Builder removeInteractionObjectList(int index) {
        if (interactionObjectListBuilder_ == null) {
          ensureInteractionObjectListIsMutable();
          interactionObjectList_.remove(index);
          onChanged();
        } else {
          interactionObjectListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public InteractionObject.Builder getInteractionObjectListBuilder(
          int index) {
        return getInteractionObjectListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public InteractionObjectOrBuilder getInteractionObjectListOrBuilder(
          int index) {
        if (interactionObjectListBuilder_ == null) {
          return interactionObjectList_.get(index);  } else {
          return interactionObjectListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public java.util.List<? extends InteractionObjectOrBuilder>
           getInteractionObjectListOrBuilderList() {
        if (interactionObjectListBuilder_ != null) {
          return interactionObjectListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(interactionObjectList_);
        }
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public InteractionObject.Builder addInteractionObjectListBuilder() {
        return getInteractionObjectListFieldBuilder().addBuilder(
            InteractionObject.getDefaultInstance());
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public InteractionObject.Builder addInteractionObjectListBuilder(
          int index) {
        return getInteractionObjectListFieldBuilder().addBuilder(
            index, InteractionObject.getDefaultInstance());
      }
      /**
       * <code>repeated .Classlink.SysWorldInterObjSetCurriculumInitRes.InteractionObject InteractionObjectList = 1;</code>
       */
      public java.util.List<InteractionObject.Builder>
           getInteractionObjectListBuilderList() {
        return getInteractionObjectListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          InteractionObject, InteractionObject.Builder, InteractionObjectOrBuilder>
          getInteractionObjectListFieldBuilder() {
        if (interactionObjectListBuilder_ == null) {
          interactionObjectListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              InteractionObject, InteractionObject.Builder, InteractionObjectOrBuilder>(
                  interactionObjectList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          interactionObjectList_ = null;
        }
        return interactionObjectListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.SysWorldInterObjSetCurriculumInitRes)
    }

    // @@protoc_insertion_point(class_scope:Classlink.SysWorldInterObjSetCurriculumInitRes)
    private static final SysWorldInterObjSetCurriculumInitRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SysWorldInterObjSetCurriculumInitRes();
    }

    public static SysWorldInterObjSetCurriculumInitRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SysWorldInterObjSetCurriculumInitRes>
        PARSER = new com.google.protobuf.AbstractParser<SysWorldInterObjSetCurriculumInitRes>() {
      @Override
      public SysWorldInterObjSetCurriculumInitRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SysWorldInterObjSetCurriculumInitRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SysWorldInterObjSetCurriculumInitRes> getParserForType() {
      return PARSER;
    }

    @Override
    public SysWorldInterObjSetCurriculumInitRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n*SysWorldInterObjSetCurriculumInitRes.p" +
      "roto\022\tClasslink\"\200\002\n$SysWorldInterObjSetC" +
      "urriculumInitRes\022`\n\025InteractionObjectLis" +
      "t\030\001 \003(\0132A.Classlink.SysWorldInterObjSetC" +
      "urriculumInitRes.InteractionObject\032v\n\021In" +
      "teractionObject\022\013\n\003Idx\030\001 \001(\005\022\014\n\004Code\030\002 \001" +
      "(\t\022\025\n\rDataTableType\030\003 \001(\t\022\017\n\007DataIdx\030\004 \001" +
      "(\005\022\020\n\010DataType\030\005 \001(\t\022\014\n\004Data\030\006 \001(\tB`\n3co" +
      "m.classlink.websocket.api.system.domain." +
      "dto.protoB)SysWorldInterObjSetCurriculum" +
      "InitResProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor,
        new String[] { "InteractionObjectList", });
    internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_descriptor =
      internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_descriptor.getNestedTypes().get(0);
    internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_SysWorldInterObjSetCurriculumInitRes_InteractionObject_descriptor,
        new String[] { "Idx", "Code", "DataTableType", "DataIdx", "DataType", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
