// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IdentityEnrollmentInfoRes.proto

package com.classlink.websocket.api.member.domain.dto.proto;

public final class IdentityEnrollmentInfoResProto {
  private IdentityEnrollmentInfoResProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentityEnrollmentInfoResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.IdentityEnrollmentInfoRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string IdentityType = 1;</code>
     * @return The identityType.
     */
    String getIdentityType();
    /**
     * <code>string IdentityType = 1;</code>
     * @return The bytes for identityType.
     */
    com.google.protobuf.ByteString
        getIdentityTypeBytes();

    /**
     * <code>int32 MeaAvartarId = 2;</code>
     * @return The meaAvartarId.
     */
    int getMeaAvartarId();

    /**
     * <code>string MemImgUrl = 3;</code>
     * @return The memImgUrl.
     */
    String getMemImgUrl();
    /**
     * <code>string MemImgUrl = 3;</code>
     * @return The bytes for memImgUrl.
     */
    com.google.protobuf.ByteString
        getMemImgUrlBytes();

    /**
     * <code>string MemNickName = 4;</code>
     * @return The memNickName.
     */
    String getMemNickName();
    /**
     * <code>string MemNickName = 4;</code>
     * @return The bytes for memNickName.
     */
    com.google.protobuf.ByteString
        getMemNickNameBytes();

    /**
     * <code>string MemName = 5;</code>
     * @return The memName.
     */
    String getMemName();
    /**
     * <code>string MemName = 5;</code>
     * @return The bytes for memName.
     */
    com.google.protobuf.ByteString
        getMemNameBytes();

    /**
     * <code>string MemEmail = 6;</code>
     * @return The memEmail.
     */
    String getMemEmail();
    /**
     * <code>string MemEmail = 6;</code>
     * @return The bytes for memEmail.
     */
    com.google.protobuf.ByteString
        getMemEmailBytes();

    /**
     * <code>string MemPhone = 7;</code>
     * @return The memPhone.
     */
    String getMemPhone();
    /**
     * <code>string MemPhone = 7;</code>
     * @return The bytes for memPhone.
     */
    com.google.protobuf.ByteString
        getMemPhoneBytes();

    /**
     * <code>string ItmRegistrationDate = 8;</code>
     * @return The itmRegistrationDate.
     */
    String getItmRegistrationDate();
    /**
     * <code>string ItmRegistrationDate = 8;</code>
     * @return The bytes for itmRegistrationDate.
     */
    com.google.protobuf.ByteString
        getItmRegistrationDateBytes();

    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @return A list containing the rtiRegistrationDateList.
     */
    java.util.List<String>
        getRtiRegistrationDateListList();
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @return The count of rtiRegistrationDateList.
     */
    int getRtiRegistrationDateListCount();
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @param index The index of the element to return.
     * @return The rtiRegistrationDateList at the given index.
     */
    String getRtiRegistrationDateList(int index);
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the rtiRegistrationDateList at the given index.
     */
    com.google.protobuf.ByteString
        getRtiRegistrationDateListBytes(int index);
  }
  /**
   * Protobuf type {@code Classlink.IdentityEnrollmentInfoRes}
   */
  public static final class IdentityEnrollmentInfoRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.IdentityEnrollmentInfoRes)
      IdentityEnrollmentInfoResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdentityEnrollmentInfoRes.newBuilder() to construct.
    private IdentityEnrollmentInfoRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdentityEnrollmentInfoRes() {
      identityType_ = "";
      memImgUrl_ = "";
      memNickName_ = "";
      memName_ = "";
      memEmail_ = "";
      memPhone_ = "";
      itmRegistrationDate_ = "";
      rtiRegistrationDateList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdentityEnrollmentInfoRes();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IdentityEnrollmentInfoResProto.internal_static_Classlink_IdentityEnrollmentInfoRes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IdentityEnrollmentInfoResProto.internal_static_Classlink_IdentityEnrollmentInfoRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IdentityEnrollmentInfoRes.class, Builder.class);
    }

    public static final int IDENTITYTYPE_FIELD_NUMBER = 1;
    private volatile Object identityType_;
    /**
     * <code>string IdentityType = 1;</code>
     * @return The identityType.
     */
    @Override
    public String getIdentityType() {
      Object ref = identityType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        identityType_ = s;
        return s;
      }
    }
    /**
     * <code>string IdentityType = 1;</code>
     * @return The bytes for identityType.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdentityTypeBytes() {
      Object ref = identityType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        identityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEAAVARTARID_FIELD_NUMBER = 2;
    private int meaAvartarId_;
    /**
     * <code>int32 MeaAvartarId = 2;</code>
     * @return The meaAvartarId.
     */
    @Override
    public int getMeaAvartarId() {
      return meaAvartarId_;
    }

    public static final int MEMIMGURL_FIELD_NUMBER = 3;
    private volatile Object memImgUrl_;
    /**
     * <code>string MemImgUrl = 3;</code>
     * @return The memImgUrl.
     */
    @Override
    public String getMemImgUrl() {
      Object ref = memImgUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        memImgUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string MemImgUrl = 3;</code>
     * @return The bytes for memImgUrl.
     */
    @Override
    public com.google.protobuf.ByteString
        getMemImgUrlBytes() {
      Object ref = memImgUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        memImgUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMNICKNAME_FIELD_NUMBER = 4;
    private volatile Object memNickName_;
    /**
     * <code>string MemNickName = 4;</code>
     * @return The memNickName.
     */
    @Override
    public String getMemNickName() {
      Object ref = memNickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        memNickName_ = s;
        return s;
      }
    }
    /**
     * <code>string MemNickName = 4;</code>
     * @return The bytes for memNickName.
     */
    @Override
    public com.google.protobuf.ByteString
        getMemNickNameBytes() {
      Object ref = memNickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        memNickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMNAME_FIELD_NUMBER = 5;
    private volatile Object memName_;
    /**
     * <code>string MemName = 5;</code>
     * @return The memName.
     */
    @Override
    public String getMemName() {
      Object ref = memName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        memName_ = s;
        return s;
      }
    }
    /**
     * <code>string MemName = 5;</code>
     * @return The bytes for memName.
     */
    @Override
    public com.google.protobuf.ByteString
        getMemNameBytes() {
      Object ref = memName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        memName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMEMAIL_FIELD_NUMBER = 6;
    private volatile Object memEmail_;
    /**
     * <code>string MemEmail = 6;</code>
     * @return The memEmail.
     */
    @Override
    public String getMemEmail() {
      Object ref = memEmail_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        memEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string MemEmail = 6;</code>
     * @return The bytes for memEmail.
     */
    @Override
    public com.google.protobuf.ByteString
        getMemEmailBytes() {
      Object ref = memEmail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        memEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMPHONE_FIELD_NUMBER = 7;
    private volatile Object memPhone_;
    /**
     * <code>string MemPhone = 7;</code>
     * @return The memPhone.
     */
    @Override
    public String getMemPhone() {
      Object ref = memPhone_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        memPhone_ = s;
        return s;
      }
    }
    /**
     * <code>string MemPhone = 7;</code>
     * @return The bytes for memPhone.
     */
    @Override
    public com.google.protobuf.ByteString
        getMemPhoneBytes() {
      Object ref = memPhone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        memPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ITMREGISTRATIONDATE_FIELD_NUMBER = 8;
    private volatile Object itmRegistrationDate_;
    /**
     * <code>string ItmRegistrationDate = 8;</code>
     * @return The itmRegistrationDate.
     */
    @Override
    public String getItmRegistrationDate() {
      Object ref = itmRegistrationDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        itmRegistrationDate_ = s;
        return s;
      }
    }
    /**
     * <code>string ItmRegistrationDate = 8;</code>
     * @return The bytes for itmRegistrationDate.
     */
    @Override
    public com.google.protobuf.ByteString
        getItmRegistrationDateBytes() {
      Object ref = itmRegistrationDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        itmRegistrationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RTIREGISTRATIONDATELIST_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList rtiRegistrationDateList_;
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @return A list containing the rtiRegistrationDateList.
     */
    public com.google.protobuf.ProtocolStringList
        getRtiRegistrationDateListList() {
      return rtiRegistrationDateList_;
    }
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @return The count of rtiRegistrationDateList.
     */
    public int getRtiRegistrationDateListCount() {
      return rtiRegistrationDateList_.size();
    }
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @param index The index of the element to return.
     * @return The rtiRegistrationDateList at the given index.
     */
    public String getRtiRegistrationDateList(int index) {
      return rtiRegistrationDateList_.get(index);
    }
    /**
     * <code>repeated string RtiRegistrationDateList = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the rtiRegistrationDateList at the given index.
     */
    public com.google.protobuf.ByteString
        getRtiRegistrationDateListBytes(int index) {
      return rtiRegistrationDateList_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(identityType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identityType_);
      }
      if (meaAvartarId_ != 0) {
        output.writeInt32(2, meaAvartarId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memImgUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, memImgUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memNickName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, memNickName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, memName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memEmail_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, memEmail_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memPhone_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, memPhone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itmRegistrationDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, itmRegistrationDate_);
      }
      for (int i = 0; i < rtiRegistrationDateList_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, rtiRegistrationDateList_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(identityType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identityType_);
      }
      if (meaAvartarId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, meaAvartarId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memImgUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, memImgUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memNickName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, memNickName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, memName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memEmail_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, memEmail_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(memPhone_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, memPhone_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(itmRegistrationDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, itmRegistrationDate_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < rtiRegistrationDateList_.size(); i++) {
          dataSize += computeStringSizeNoTag(rtiRegistrationDateList_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRtiRegistrationDateListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IdentityEnrollmentInfoRes)) {
        return super.equals(obj);
      }
      IdentityEnrollmentInfoRes other = (IdentityEnrollmentInfoRes) obj;

      if (!getIdentityType()
          .equals(other.getIdentityType())) return false;
      if (getMeaAvartarId()
          != other.getMeaAvartarId()) return false;
      if (!getMemImgUrl()
          .equals(other.getMemImgUrl())) return false;
      if (!getMemNickName()
          .equals(other.getMemNickName())) return false;
      if (!getMemName()
          .equals(other.getMemName())) return false;
      if (!getMemEmail()
          .equals(other.getMemEmail())) return false;
      if (!getMemPhone()
          .equals(other.getMemPhone())) return false;
      if (!getItmRegistrationDate()
          .equals(other.getItmRegistrationDate())) return false;
      if (!getRtiRegistrationDateListList()
          .equals(other.getRtiRegistrationDateListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDENTITYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityType().hashCode();
      hash = (37 * hash) + MEAAVARTARID_FIELD_NUMBER;
      hash = (53 * hash) + getMeaAvartarId();
      hash = (37 * hash) + MEMIMGURL_FIELD_NUMBER;
      hash = (53 * hash) + getMemImgUrl().hashCode();
      hash = (37 * hash) + MEMNICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMemNickName().hashCode();
      hash = (37 * hash) + MEMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMemName().hashCode();
      hash = (37 * hash) + MEMEMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getMemEmail().hashCode();
      hash = (37 * hash) + MEMPHONE_FIELD_NUMBER;
      hash = (53 * hash) + getMemPhone().hashCode();
      hash = (37 * hash) + ITMREGISTRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getItmRegistrationDate().hashCode();
      if (getRtiRegistrationDateListCount() > 0) {
        hash = (37 * hash) + RTIREGISTRATIONDATELIST_FIELD_NUMBER;
        hash = (53 * hash) + getRtiRegistrationDateListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IdentityEnrollmentInfoRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityEnrollmentInfoRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityEnrollmentInfoRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IdentityEnrollmentInfoRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IdentityEnrollmentInfoRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IdentityEnrollmentInfoRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IdentityEnrollmentInfoRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.IdentityEnrollmentInfoRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.IdentityEnrollmentInfoRes)
        IdentityEnrollmentInfoResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IdentityEnrollmentInfoResProto.internal_static_Classlink_IdentityEnrollmentInfoRes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IdentityEnrollmentInfoResProto.internal_static_Classlink_IdentityEnrollmentInfoRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IdentityEnrollmentInfoRes.class, Builder.class);
      }

      // Construct using com.classlink.websocket.api.member.domain.dto.proto.IdentityEnrollmentInfoResProto.IdentityEnrollmentInfoRes.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        identityType_ = "";

        meaAvartarId_ = 0;

        memImgUrl_ = "";

        memNickName_ = "";

        memName_ = "";

        memEmail_ = "";

        memPhone_ = "";

        itmRegistrationDate_ = "";

        rtiRegistrationDateList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IdentityEnrollmentInfoResProto.internal_static_Classlink_IdentityEnrollmentInfoRes_descriptor;
      }

      @Override
      public IdentityEnrollmentInfoRes getDefaultInstanceForType() {
        return IdentityEnrollmentInfoRes.getDefaultInstance();
      }

      @Override
      public IdentityEnrollmentInfoRes build() {
        IdentityEnrollmentInfoRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public IdentityEnrollmentInfoRes buildPartial() {
        IdentityEnrollmentInfoRes result = new IdentityEnrollmentInfoRes(this);
        int from_bitField0_ = bitField0_;
        result.identityType_ = identityType_;
        result.meaAvartarId_ = meaAvartarId_;
        result.memImgUrl_ = memImgUrl_;
        result.memNickName_ = memNickName_;
        result.memName_ = memName_;
        result.memEmail_ = memEmail_;
        result.memPhone_ = memPhone_;
        result.itmRegistrationDate_ = itmRegistrationDate_;
        if (((bitField0_ & 0x00000001) != 0)) {
          rtiRegistrationDateList_ = rtiRegistrationDateList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.rtiRegistrationDateList_ = rtiRegistrationDateList_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IdentityEnrollmentInfoRes) {
          return mergeFrom((IdentityEnrollmentInfoRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IdentityEnrollmentInfoRes other) {
        if (other == IdentityEnrollmentInfoRes.getDefaultInstance()) return this;
        if (!other.getIdentityType().isEmpty()) {
          identityType_ = other.identityType_;
          onChanged();
        }
        if (other.getMeaAvartarId() != 0) {
          setMeaAvartarId(other.getMeaAvartarId());
        }
        if (!other.getMemImgUrl().isEmpty()) {
          memImgUrl_ = other.memImgUrl_;
          onChanged();
        }
        if (!other.getMemNickName().isEmpty()) {
          memNickName_ = other.memNickName_;
          onChanged();
        }
        if (!other.getMemName().isEmpty()) {
          memName_ = other.memName_;
          onChanged();
        }
        if (!other.getMemEmail().isEmpty()) {
          memEmail_ = other.memEmail_;
          onChanged();
        }
        if (!other.getMemPhone().isEmpty()) {
          memPhone_ = other.memPhone_;
          onChanged();
        }
        if (!other.getItmRegistrationDate().isEmpty()) {
          itmRegistrationDate_ = other.itmRegistrationDate_;
          onChanged();
        }
        if (!other.rtiRegistrationDateList_.isEmpty()) {
          if (rtiRegistrationDateList_.isEmpty()) {
            rtiRegistrationDateList_ = other.rtiRegistrationDateList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRtiRegistrationDateListIsMutable();
            rtiRegistrationDateList_.addAll(other.rtiRegistrationDateList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                identityType_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                meaAvartarId_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                memImgUrl_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                memNickName_ = input.readStringRequireUtf8();

                break;
              } // case 34
              case 42: {
                memName_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 50: {
                memEmail_ = input.readStringRequireUtf8();

                break;
              } // case 50
              case 58: {
                memPhone_ = input.readStringRequireUtf8();

                break;
              } // case 58
              case 66: {
                itmRegistrationDate_ = input.readStringRequireUtf8();

                break;
              } // case 66
              case 74: {
                String s = input.readStringRequireUtf8();
                ensureRtiRegistrationDateListIsMutable();
                rtiRegistrationDateList_.add(s);
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object identityType_ = "";
      /**
       * <code>string IdentityType = 1;</code>
       * @return The identityType.
       */
      public String getIdentityType() {
        Object ref = identityType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          identityType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string IdentityType = 1;</code>
       * @return The bytes for identityType.
       */
      public com.google.protobuf.ByteString
          getIdentityTypeBytes() {
        Object ref = identityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          identityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string IdentityType = 1;</code>
       * @param value The identityType to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string IdentityType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentityType() {
        
        identityType_ = getDefaultInstance().getIdentityType();
        onChanged();
        return this;
      }
      /**
       * <code>string IdentityType = 1;</code>
       * @param value The bytes for identityType to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identityType_ = value;
        onChanged();
        return this;
      }

      private int meaAvartarId_ ;
      /**
       * <code>int32 MeaAvartarId = 2;</code>
       * @return The meaAvartarId.
       */
      @Override
      public int getMeaAvartarId() {
        return meaAvartarId_;
      }
      /**
       * <code>int32 MeaAvartarId = 2;</code>
       * @param value The meaAvartarId to set.
       * @return This builder for chaining.
       */
      public Builder setMeaAvartarId(int value) {
        
        meaAvartarId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 MeaAvartarId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMeaAvartarId() {
        
        meaAvartarId_ = 0;
        onChanged();
        return this;
      }

      private Object memImgUrl_ = "";
      /**
       * <code>string MemImgUrl = 3;</code>
       * @return The memImgUrl.
       */
      public String getMemImgUrl() {
        Object ref = memImgUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          memImgUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string MemImgUrl = 3;</code>
       * @return The bytes for memImgUrl.
       */
      public com.google.protobuf.ByteString
          getMemImgUrlBytes() {
        Object ref = memImgUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          memImgUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MemImgUrl = 3;</code>
       * @param value The memImgUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMemImgUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memImgUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MemImgUrl = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemImgUrl() {
        
        memImgUrl_ = getDefaultInstance().getMemImgUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string MemImgUrl = 3;</code>
       * @param value The bytes for memImgUrl to set.
       * @return This builder for chaining.
       */
      public Builder setMemImgUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memImgUrl_ = value;
        onChanged();
        return this;
      }

      private Object memNickName_ = "";
      /**
       * <code>string MemNickName = 4;</code>
       * @return The memNickName.
       */
      public String getMemNickName() {
        Object ref = memNickName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          memNickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string MemNickName = 4;</code>
       * @return The bytes for memNickName.
       */
      public com.google.protobuf.ByteString
          getMemNickNameBytes() {
        Object ref = memNickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          memNickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MemNickName = 4;</code>
       * @param value The memNickName to set.
       * @return This builder for chaining.
       */
      public Builder setMemNickName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memNickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MemNickName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemNickName() {
        
        memNickName_ = getDefaultInstance().getMemNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string MemNickName = 4;</code>
       * @param value The bytes for memNickName to set.
       * @return This builder for chaining.
       */
      public Builder setMemNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memNickName_ = value;
        onChanged();
        return this;
      }

      private Object memName_ = "";
      /**
       * <code>string MemName = 5;</code>
       * @return The memName.
       */
      public String getMemName() {
        Object ref = memName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          memName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string MemName = 5;</code>
       * @return The bytes for memName.
       */
      public com.google.protobuf.ByteString
          getMemNameBytes() {
        Object ref = memName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          memName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MemName = 5;</code>
       * @param value The memName to set.
       * @return This builder for chaining.
       */
      public Builder setMemName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MemName = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemName() {
        
        memName_ = getDefaultInstance().getMemName();
        onChanged();
        return this;
      }
      /**
       * <code>string MemName = 5;</code>
       * @param value The bytes for memName to set.
       * @return This builder for chaining.
       */
      public Builder setMemNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memName_ = value;
        onChanged();
        return this;
      }

      private Object memEmail_ = "";
      /**
       * <code>string MemEmail = 6;</code>
       * @return The memEmail.
       */
      public String getMemEmail() {
        Object ref = memEmail_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          memEmail_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string MemEmail = 6;</code>
       * @return The bytes for memEmail.
       */
      public com.google.protobuf.ByteString
          getMemEmailBytes() {
        Object ref = memEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          memEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MemEmail = 6;</code>
       * @param value The memEmail to set.
       * @return This builder for chaining.
       */
      public Builder setMemEmail(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MemEmail = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemEmail() {
        
        memEmail_ = getDefaultInstance().getMemEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string MemEmail = 6;</code>
       * @param value The bytes for memEmail to set.
       * @return This builder for chaining.
       */
      public Builder setMemEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memEmail_ = value;
        onChanged();
        return this;
      }

      private Object memPhone_ = "";
      /**
       * <code>string MemPhone = 7;</code>
       * @return The memPhone.
       */
      public String getMemPhone() {
        Object ref = memPhone_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          memPhone_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string MemPhone = 7;</code>
       * @return The bytes for memPhone.
       */
      public com.google.protobuf.ByteString
          getMemPhoneBytes() {
        Object ref = memPhone_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          memPhone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MemPhone = 7;</code>
       * @param value The memPhone to set.
       * @return This builder for chaining.
       */
      public Builder setMemPhone(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        memPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MemPhone = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemPhone() {
        
        memPhone_ = getDefaultInstance().getMemPhone();
        onChanged();
        return this;
      }
      /**
       * <code>string MemPhone = 7;</code>
       * @param value The bytes for memPhone to set.
       * @return This builder for chaining.
       */
      public Builder setMemPhoneBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        memPhone_ = value;
        onChanged();
        return this;
      }

      private Object itmRegistrationDate_ = "";
      /**
       * <code>string ItmRegistrationDate = 8;</code>
       * @return The itmRegistrationDate.
       */
      public String getItmRegistrationDate() {
        Object ref = itmRegistrationDate_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          itmRegistrationDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ItmRegistrationDate = 8;</code>
       * @return The bytes for itmRegistrationDate.
       */
      public com.google.protobuf.ByteString
          getItmRegistrationDateBytes() {
        Object ref = itmRegistrationDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          itmRegistrationDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ItmRegistrationDate = 8;</code>
       * @param value The itmRegistrationDate to set.
       * @return This builder for chaining.
       */
      public Builder setItmRegistrationDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        itmRegistrationDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ItmRegistrationDate = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearItmRegistrationDate() {
        
        itmRegistrationDate_ = getDefaultInstance().getItmRegistrationDate();
        onChanged();
        return this;
      }
      /**
       * <code>string ItmRegistrationDate = 8;</code>
       * @param value The bytes for itmRegistrationDate to set.
       * @return This builder for chaining.
       */
      public Builder setItmRegistrationDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        itmRegistrationDate_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList rtiRegistrationDateList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRtiRegistrationDateListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          rtiRegistrationDateList_ = new com.google.protobuf.LazyStringArrayList(rtiRegistrationDateList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @return A list containing the rtiRegistrationDateList.
       */
      public com.google.protobuf.ProtocolStringList
          getRtiRegistrationDateListList() {
        return rtiRegistrationDateList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @return The count of rtiRegistrationDateList.
       */
      public int getRtiRegistrationDateListCount() {
        return rtiRegistrationDateList_.size();
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @param index The index of the element to return.
       * @return The rtiRegistrationDateList at the given index.
       */
      public String getRtiRegistrationDateList(int index) {
        return rtiRegistrationDateList_.get(index);
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @param index The index of the value to return.
       * @return The bytes of the rtiRegistrationDateList at the given index.
       */
      public com.google.protobuf.ByteString
          getRtiRegistrationDateListBytes(int index) {
        return rtiRegistrationDateList_.getByteString(index);
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @param index The index to set the value at.
       * @param value The rtiRegistrationDateList to set.
       * @return This builder for chaining.
       */
      public Builder setRtiRegistrationDateList(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRtiRegistrationDateListIsMutable();
        rtiRegistrationDateList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @param value The rtiRegistrationDateList to add.
       * @return This builder for chaining.
       */
      public Builder addRtiRegistrationDateList(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRtiRegistrationDateListIsMutable();
        rtiRegistrationDateList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @param values The rtiRegistrationDateList to add.
       * @return This builder for chaining.
       */
      public Builder addAllRtiRegistrationDateList(
          Iterable<String> values) {
        ensureRtiRegistrationDateListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, rtiRegistrationDateList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRtiRegistrationDateList() {
        rtiRegistrationDateList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string RtiRegistrationDateList = 9;</code>
       * @param value The bytes of the rtiRegistrationDateList to add.
       * @return This builder for chaining.
       */
      public Builder addRtiRegistrationDateListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRtiRegistrationDateListIsMutable();
        rtiRegistrationDateList_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.IdentityEnrollmentInfoRes)
    }

    // @@protoc_insertion_point(class_scope:Classlink.IdentityEnrollmentInfoRes)
    private static final IdentityEnrollmentInfoRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IdentityEnrollmentInfoRes();
    }

    public static IdentityEnrollmentInfoRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdentityEnrollmentInfoRes>
        PARSER = new com.google.protobuf.AbstractParser<IdentityEnrollmentInfoRes>() {
      @Override
      public IdentityEnrollmentInfoRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IdentityEnrollmentInfoRes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IdentityEnrollmentInfoRes> getParserForType() {
      return PARSER;
    }

    @Override
    public IdentityEnrollmentInfoRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_IdentityEnrollmentInfoRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_IdentityEnrollmentInfoRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037IdentityEnrollmentInfoRes.proto\022\tClass" +
      "link\"\342\001\n\031IdentityEnrollmentInfoRes\022\024\n\014Id" +
      "entityType\030\001 \001(\t\022\024\n\014MeaAvartarId\030\002 \001(\005\022\021" +
      "\n\tMemImgUrl\030\003 \001(\t\022\023\n\013MemNickName\030\004 \001(\t\022\017" +
      "\n\007MemName\030\005 \001(\t\022\020\n\010MemEmail\030\006 \001(\t\022\020\n\010Mem" +
      "Phone\030\007 \001(\t\022\033\n\023ItmRegistrationDate\030\010 \001(\t" +
      "\022\037\n\027RtiRegistrationDateList\030\t \003(\tBU\n3com" +
      ".classlink.websocket.api.member.domain.d" +
      "to.protoB\036IdentityEnrollmentInfoResProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_IdentityEnrollmentInfoRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_IdentityEnrollmentInfoRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_IdentityEnrollmentInfoRes_descriptor,
        new String[] { "IdentityType", "MeaAvartarId", "MemImgUrl", "MemNickName", "MemName", "MemEmail", "MemPhone", "ItmRegistrationDate", "RtiRegistrationDateList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
