// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IdentityListRes.proto

package com.classlink.websocket.api.member.domain.dto.proto;

public final class IdentityListResProto {
  private IdentityListResProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentityListResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.IdentityListRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @return A list containing the identityTypes.
     */
    java.util.List<java.lang.String>
        getIdentityTypesList();
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @return The count of identityTypes.
     */
    int getIdentityTypesCount();
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @param index The index of the element to return.
     * @return The identityTypes at the given index.
     */
    java.lang.String getIdentityTypes(int index);
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the identityTypes at the given index.
     */
    com.google.protobuf.ByteString
        getIdentityTypesBytes(int index);
  }
  /**
   * Protobuf type {@code Classlink.IdentityListRes}
   */
  public static final class IdentityListRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.IdentityListRes)
      IdentityListResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdentityListRes.newBuilder() to construct.
    private IdentityListRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdentityListRes() {
      identityTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdentityListRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.internal_static_Classlink_IdentityListRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.internal_static_Classlink_IdentityListRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.class, com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.Builder.class);
    }

    public static final int IDENTITYTYPES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList identityTypes_;
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @return A list containing the identityTypes.
     */
    public com.google.protobuf.ProtocolStringList
        getIdentityTypesList() {
      return identityTypes_;
    }
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @return The count of identityTypes.
     */
    public int getIdentityTypesCount() {
      return identityTypes_.size();
    }
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @param index The index of the element to return.
     * @return The identityTypes at the given index.
     */
    public java.lang.String getIdentityTypes(int index) {
      return identityTypes_.get(index);
    }
    /**
     * <code>repeated string IdentityTypes = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the identityTypes at the given index.
     */
    public com.google.protobuf.ByteString
        getIdentityTypesBytes(int index) {
      return identityTypes_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < identityTypes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identityTypes_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < identityTypes_.size(); i++) {
          dataSize += computeStringSizeNoTag(identityTypes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdentityTypesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes)) {
        return super.equals(obj);
      }
      com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes other = (com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes) obj;

      if (!getIdentityTypesList()
          .equals(other.getIdentityTypesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdentityTypesCount() > 0) {
        hash = (37 * hash) + IDENTITYTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getIdentityTypesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.IdentityListRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.IdentityListRes)
        com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.internal_static_Classlink_IdentityListRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.internal_static_Classlink_IdentityListRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.class, com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.Builder.class);
      }

      // Construct using com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        identityTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.internal_static_Classlink_IdentityListRes_descriptor;
      }

      @java.lang.Override
      public com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes getDefaultInstanceForType() {
        return com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes build() {
        com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes buildPartial() {
        com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes result = new com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          identityTypes_ = identityTypes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.identityTypes_ = identityTypes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes) {
          return mergeFrom((com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes other) {
        if (other == com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes.getDefaultInstance()) return this;
        if (!other.identityTypes_.isEmpty()) {
          if (identityTypes_.isEmpty()) {
            identityTypes_ = other.identityTypes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdentityTypesIsMutable();
            identityTypes_.addAll(other.identityTypes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureIdentityTypesIsMutable();
                identityTypes_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList identityTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdentityTypesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          identityTypes_ = new com.google.protobuf.LazyStringArrayList(identityTypes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @return A list containing the identityTypes.
       */
      public com.google.protobuf.ProtocolStringList
          getIdentityTypesList() {
        return identityTypes_.getUnmodifiableView();
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @return The count of identityTypes.
       */
      public int getIdentityTypesCount() {
        return identityTypes_.size();
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @param index The index of the element to return.
       * @return The identityTypes at the given index.
       */
      public java.lang.String getIdentityTypes(int index) {
        return identityTypes_.get(index);
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the identityTypes at the given index.
       */
      public com.google.protobuf.ByteString
          getIdentityTypesBytes(int index) {
        return identityTypes_.getByteString(index);
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @param index The index to set the value at.
       * @param value The identityTypes to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityTypes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdentityTypesIsMutable();
        identityTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @param value The identityTypes to add.
       * @return This builder for chaining.
       */
      public Builder addIdentityTypes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdentityTypesIsMutable();
        identityTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @param values The identityTypes to add.
       * @return This builder for chaining.
       */
      public Builder addAllIdentityTypes(
          java.lang.Iterable<java.lang.String> values) {
        ensureIdentityTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, identityTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentityTypes() {
        identityTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string IdentityTypes = 1;</code>
       * @param value The bytes of the identityTypes to add.
       * @return This builder for chaining.
       */
      public Builder addIdentityTypesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIdentityTypesIsMutable();
        identityTypes_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.IdentityListRes)
    }

    // @@protoc_insertion_point(class_scope:Classlink.IdentityListRes)
    private static final com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes();
    }

    public static com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdentityListRes>
        PARSER = new com.google.protobuf.AbstractParser<IdentityListRes>() {
      @java.lang.Override
      public IdentityListRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IdentityListRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdentityListRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classlink.websocket.api.member.domain.dto.proto.IdentityListResProto.IdentityListRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_IdentityListRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_IdentityListRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025IdentityListRes.proto\022\tClasslink\"(\n\017Id" +
      "entityListRes\022\025\n\rIdentityTypes\030\001 \003(\tBK\n3" +
      "com.classlink.websocket.api.member.domai" +
      "n.dto.protoB\024IdentityListResProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_IdentityListRes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_IdentityListRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_IdentityListRes_descriptor,
        new java.lang.String[] { "IdentityTypes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
