// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CWclassPacket.proto

package com.classlink.websocket.api.common.domain;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CWclassPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.CWclassPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 OpCode = 1;</code>
     * @return The opCode.
     */
    int getOpCode();

    /**
     * <code>string AccessToken = 2;</code>
     * @return The accessToken.
     */
    java.lang.String getAccessToken();
    /**
     * <code>string AccessToken = 2;</code>
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>int32 InstanceId = 3;</code>
     * @return The instanceId.
     */
    int getInstanceId();

    /**
     * <code>bytes Data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code Classlink.CWclassPacket}
   */
  public static final class CWclassPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.CWclassPacket)
      CWclassPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CWclassPacket.newBuilder() to construct.
    private CWclassPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CWclassPacket() {
      accessToken_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CWclassPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classlink.websocket.api.common.domain.Packet.internal_static_Classlink_CWclassPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classlink.websocket.api.common.domain.Packet.internal_static_Classlink_CWclassPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classlink.websocket.api.common.domain.Packet.CWclassPacket.class, com.classlink.websocket.api.common.domain.Packet.CWclassPacket.Builder.class);
    }

    public static final int OPCODE_FIELD_NUMBER = 1;
    private int opCode_;
    /**
     * <code>int32 OpCode = 1;</code>
     * @return The opCode.
     */
    @java.lang.Override
    public int getOpCode() {
      return opCode_;
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string AccessToken = 2;</code>
     * @return The accessToken.
     */
    @java.lang.Override
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string AccessToken = 2;</code>
     * @return The bytes for accessToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INSTANCEID_FIELD_NUMBER = 3;
    private int instanceId_;
    /**
     * <code>int32 InstanceId = 3;</code>
     * @return The instanceId.
     */
    @java.lang.Override
    public int getInstanceId() {
      return instanceId_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes Data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (opCode_ != 0) {
        output.writeInt32(1, opCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, accessToken_);
      }
      if (instanceId_ != 0) {
        output.writeInt32(3, instanceId_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (opCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, opCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, accessToken_);
      }
      if (instanceId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, instanceId_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classlink.websocket.api.common.domain.Packet.CWclassPacket)) {
        return super.equals(obj);
      }
      com.classlink.websocket.api.common.domain.Packet.CWclassPacket other = (com.classlink.websocket.api.common.domain.Packet.CWclassPacket) obj;

      if (getOpCode()
          != other.getOpCode()) return false;
      if (!getAccessToken()
          .equals(other.getAccessToken())) return false;
      if (getInstanceId()
          != other.getInstanceId()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPCODE_FIELD_NUMBER;
      hash = (53 * hash) + getOpCode();
      hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
      hash = (53 * hash) + getInstanceId();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classlink.websocket.api.common.domain.Packet.CWclassPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.CWclassPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.CWclassPacket)
        com.classlink.websocket.api.common.domain.Packet.CWclassPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classlink.websocket.api.common.domain.Packet.internal_static_Classlink_CWclassPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classlink.websocket.api.common.domain.Packet.internal_static_Classlink_CWclassPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classlink.websocket.api.common.domain.Packet.CWclassPacket.class, com.classlink.websocket.api.common.domain.Packet.CWclassPacket.Builder.class);
      }

      // Construct using com.classlink.websocket.api.common.domain.Packet.CWclassPacket.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        opCode_ = 0;

        accessToken_ = "";

        instanceId_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classlink.websocket.api.common.domain.Packet.internal_static_Classlink_CWclassPacket_descriptor;
      }

      @java.lang.Override
      public com.classlink.websocket.api.common.domain.Packet.CWclassPacket getDefaultInstanceForType() {
        return com.classlink.websocket.api.common.domain.Packet.CWclassPacket.getDefaultInstance();
      }

      @java.lang.Override
      public com.classlink.websocket.api.common.domain.Packet.CWclassPacket build() {
        com.classlink.websocket.api.common.domain.Packet.CWclassPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classlink.websocket.api.common.domain.Packet.CWclassPacket buildPartial() {
        com.classlink.websocket.api.common.domain.Packet.CWclassPacket result = new com.classlink.websocket.api.common.domain.Packet.CWclassPacket(this);
        result.opCode_ = opCode_;
        result.accessToken_ = accessToken_;
        result.instanceId_ = instanceId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classlink.websocket.api.common.domain.Packet.CWclassPacket) {
          return mergeFrom((com.classlink.websocket.api.common.domain.Packet.CWclassPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classlink.websocket.api.common.domain.Packet.CWclassPacket other) {
        if (other == com.classlink.websocket.api.common.domain.Packet.CWclassPacket.getDefaultInstance()) return this;
        if (other.getOpCode() != 0) {
          setOpCode(other.getOpCode());
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (other.getInstanceId() != 0) {
          setInstanceId(other.getInstanceId());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                opCode_ = input.readInt32();

                break;
              } // case 8
              case 18: {
                accessToken_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                instanceId_ = input.readInt32();

                break;
              } // case 24
              case 34: {
                data_ = input.readBytes();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int opCode_ ;
      /**
       * <code>int32 OpCode = 1;</code>
       * @return The opCode.
       */
      @java.lang.Override
      public int getOpCode() {
        return opCode_;
      }
      /**
       * <code>int32 OpCode = 1;</code>
       * @param value The opCode to set.
       * @return This builder for chaining.
       */
      public Builder setOpCode(int value) {
        
        opCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 OpCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpCode() {
        
        opCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string AccessToken = 2;</code>
       * @return The accessToken.
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string AccessToken = 2;</code>
       * @return The bytes for accessToken.
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string AccessToken = 2;</code>
       * @param value The accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string AccessToken = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string AccessToken = 2;</code>
       * @param value The bytes for accessToken to set.
       * @return This builder for chaining.
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private int instanceId_ ;
      /**
       * <code>int32 InstanceId = 3;</code>
       * @return The instanceId.
       */
      @java.lang.Override
      public int getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>int32 InstanceId = 3;</code>
       * @param value The instanceId to set.
       * @return This builder for chaining.
       */
      public Builder setInstanceId(int value) {
        
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 InstanceId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInstanceId() {
        
        instanceId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Data = 4;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes Data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.CWclassPacket)
    }

    // @@protoc_insertion_point(class_scope:Classlink.CWclassPacket)
    private static final com.classlink.websocket.api.common.domain.Packet.CWclassPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classlink.websocket.api.common.domain.Packet.CWclassPacket();
    }

    public static com.classlink.websocket.api.common.domain.Packet.CWclassPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CWclassPacket>
        PARSER = new com.google.protobuf.AbstractParser<CWclassPacket>() {
      @java.lang.Override
      public CWclassPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CWclassPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CWclassPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classlink.websocket.api.common.domain.Packet.CWclassPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_CWclassPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_CWclassPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CWclassPacket.proto\022\tClasslink\"V\n\rCWcl" +
      "assPacket\022\016\n\006OpCode\030\001 \001(\005\022\023\n\013AccessToken" +
      "\030\002 \001(\t\022\022\n\nInstanceId\030\003 \001(\005\022\014\n\004Data\030\004 \001(\014" +
      "B3\n)com.classlink.websocket.api.common.d" +
      "omainB\006Packetb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_CWclassPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_CWclassPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_CWclassPacket_descriptor,
        new java.lang.String[] { "OpCode", "AccessToken", "InstanceId", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
