// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LobbyHomeClassInfoListReq.proto

package com.classlink.websocket.api.lobby.domain.param.proto;

public final class LobbyHomeClassInfoListReqProto {
  private LobbyHomeClassInfoListReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LobbyHomeClassInfoListReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.LobbyHomeClassInfoListReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string InsCode = 1;</code>
     * @return The insCode.
     */
    java.lang.String getInsCode();
    /**
     * <code>string InsCode = 1;</code>
     * @return The bytes for insCode.
     */
    com.google.protobuf.ByteString
        getInsCodeBytes();

    /**
     * <code>string IdentityType = 2;</code>
     * @return The identityType.
     */
    java.lang.String getIdentityType();
    /**
     * <code>string IdentityType = 2;</code>
     * @return The bytes for identityType.
     */
    com.google.protobuf.ByteString
        getIdentityTypeBytes();

    /**
     * <code>string StartDate = 3;</code>
     * @return The startDate.
     */
    java.lang.String getStartDate();
    /**
     * <code>string StartDate = 3;</code>
     * @return The bytes for startDate.
     */
    com.google.protobuf.ByteString
        getStartDateBytes();

    /**
     * <code>string EndDate = 4;</code>
     * @return The endDate.
     */
    java.lang.String getEndDate();
    /**
     * <code>string EndDate = 4;</code>
     * @return The bytes for endDate.
     */
    com.google.protobuf.ByteString
        getEndDateBytes();
  }
  /**
   * Protobuf type {@code Classlink.LobbyHomeClassInfoListReq}
   */
  public static final class LobbyHomeClassInfoListReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.LobbyHomeClassInfoListReq)
      LobbyHomeClassInfoListReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LobbyHomeClassInfoListReq.newBuilder() to construct.
    private LobbyHomeClassInfoListReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LobbyHomeClassInfoListReq() {
      insCode_ = "";
      identityType_ = "";
      startDate_ = "";
      endDate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LobbyHomeClassInfoListReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.internal_static_Classlink_LobbyHomeClassInfoListReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.internal_static_Classlink_LobbyHomeClassInfoListReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.class, com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.Builder.class);
    }

    public static final int INSCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object insCode_;
    /**
     * <code>string InsCode = 1;</code>
     * @return The insCode.
     */
    @java.lang.Override
    public java.lang.String getInsCode() {
      java.lang.Object ref = insCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        insCode_ = s;
        return s;
      }
    }
    /**
     * <code>string InsCode = 1;</code>
     * @return The bytes for insCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInsCodeBytes() {
      java.lang.Object ref = insCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        insCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTITYTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object identityType_;
    /**
     * <code>string IdentityType = 2;</code>
     * @return The identityType.
     */
    @java.lang.Override
    public java.lang.String getIdentityType() {
      java.lang.Object ref = identityType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identityType_ = s;
        return s;
      }
    }
    /**
     * <code>string IdentityType = 2;</code>
     * @return The bytes for identityType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentityTypeBytes() {
      java.lang.Object ref = identityType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identityType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTDATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object startDate_;
    /**
     * <code>string StartDate = 3;</code>
     * @return The startDate.
     */
    @java.lang.Override
    public java.lang.String getStartDate() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startDate_ = s;
        return s;
      }
    }
    /**
     * <code>string StartDate = 3;</code>
     * @return The bytes for startDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStartDateBytes() {
      java.lang.Object ref = startDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDDATE_FIELD_NUMBER = 4;
    private volatile java.lang.Object endDate_;
    /**
     * <code>string EndDate = 4;</code>
     * @return The endDate.
     */
    @java.lang.Override
    public java.lang.String getEndDate() {
      java.lang.Object ref = endDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endDate_ = s;
        return s;
      }
    }
    /**
     * <code>string EndDate = 4;</code>
     * @return The bytes for endDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEndDateBytes() {
      java.lang.Object ref = endDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(insCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, insCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(identityType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, identityType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, startDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, endDate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(insCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, insCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(identityType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, identityType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, startDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, endDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq)) {
        return super.equals(obj);
      }
      com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq other = (com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq) obj;

      if (!getInsCode()
          .equals(other.getInsCode())) return false;
      if (!getIdentityType()
          .equals(other.getIdentityType())) return false;
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
      if (!getEndDate()
          .equals(other.getEndDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getInsCode().hashCode();
      hash = (37 * hash) + IDENTITYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getIdentityType().hashCode();
      hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
      hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.LobbyHomeClassInfoListReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.LobbyHomeClassInfoListReq)
        com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.internal_static_Classlink_LobbyHomeClassInfoListReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.internal_static_Classlink_LobbyHomeClassInfoListReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.class, com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.Builder.class);
      }

      // Construct using com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        insCode_ = "";

        identityType_ = "";

        startDate_ = "";

        endDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.internal_static_Classlink_LobbyHomeClassInfoListReq_descriptor;
      }

      @java.lang.Override
      public com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq getDefaultInstanceForType() {
        return com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq build() {
        com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq buildPartial() {
        com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq result = new com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq(this);
        result.insCode_ = insCode_;
        result.identityType_ = identityType_;
        result.startDate_ = startDate_;
        result.endDate_ = endDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq) {
          return mergeFrom((com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq other) {
        if (other == com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq.getDefaultInstance()) return this;
        if (!other.getInsCode().isEmpty()) {
          insCode_ = other.insCode_;
          onChanged();
        }
        if (!other.getIdentityType().isEmpty()) {
          identityType_ = other.identityType_;
          onChanged();
        }
        if (!other.getStartDate().isEmpty()) {
          startDate_ = other.startDate_;
          onChanged();
        }
        if (!other.getEndDate().isEmpty()) {
          endDate_ = other.endDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                insCode_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                identityType_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                startDate_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                endDate_ = input.readStringRequireUtf8();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object insCode_ = "";
      /**
       * <code>string InsCode = 1;</code>
       * @return The insCode.
       */
      public java.lang.String getInsCode() {
        java.lang.Object ref = insCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          insCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string InsCode = 1;</code>
       * @return The bytes for insCode.
       */
      public com.google.protobuf.ByteString
          getInsCodeBytes() {
        java.lang.Object ref = insCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          insCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string InsCode = 1;</code>
       * @param value The insCode to set.
       * @return This builder for chaining.
       */
      public Builder setInsCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        insCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string InsCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearInsCode() {
        
        insCode_ = getDefaultInstance().getInsCode();
        onChanged();
        return this;
      }
      /**
       * <code>string InsCode = 1;</code>
       * @param value The bytes for insCode to set.
       * @return This builder for chaining.
       */
      public Builder setInsCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        insCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object identityType_ = "";
      /**
       * <code>string IdentityType = 2;</code>
       * @return The identityType.
       */
      public java.lang.String getIdentityType() {
        java.lang.Object ref = identityType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identityType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string IdentityType = 2;</code>
       * @return The bytes for identityType.
       */
      public com.google.protobuf.ByteString
          getIdentityTypeBytes() {
        java.lang.Object ref = identityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string IdentityType = 2;</code>
       * @param value The identityType to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string IdentityType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentityType() {
        
        identityType_ = getDefaultInstance().getIdentityType();
        onChanged();
        return this;
      }
      /**
       * <code>string IdentityType = 2;</code>
       * @param value The bytes for identityType to set.
       * @return This builder for chaining.
       */
      public Builder setIdentityTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identityType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startDate_ = "";
      /**
       * <code>string StartDate = 3;</code>
       * @return The startDate.
       */
      public java.lang.String getStartDate() {
        java.lang.Object ref = startDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string StartDate = 3;</code>
       * @return The bytes for startDate.
       */
      public com.google.protobuf.ByteString
          getStartDateBytes() {
        java.lang.Object ref = startDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string StartDate = 3;</code>
       * @param value The startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string StartDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartDate() {
        
        startDate_ = getDefaultInstance().getStartDate();
        onChanged();
        return this;
      }
      /**
       * <code>string StartDate = 3;</code>
       * @param value The bytes for startDate to set.
       * @return This builder for chaining.
       */
      public Builder setStartDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endDate_ = "";
      /**
       * <code>string EndDate = 4;</code>
       * @return The endDate.
       */
      public java.lang.String getEndDate() {
        java.lang.Object ref = endDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string EndDate = 4;</code>
       * @return The bytes for endDate.
       */
      public com.google.protobuf.ByteString
          getEndDateBytes() {
        java.lang.Object ref = endDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string EndDate = 4;</code>
       * @param value The endDate to set.
       * @return This builder for chaining.
       */
      public Builder setEndDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string EndDate = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndDate() {
        
        endDate_ = getDefaultInstance().getEndDate();
        onChanged();
        return this;
      }
      /**
       * <code>string EndDate = 4;</code>
       * @param value The bytes for endDate to set.
       * @return This builder for chaining.
       */
      public Builder setEndDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.LobbyHomeClassInfoListReq)
    }

    // @@protoc_insertion_point(class_scope:Classlink.LobbyHomeClassInfoListReq)
    private static final com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq();
    }

    public static com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LobbyHomeClassInfoListReq>
        PARSER = new com.google.protobuf.AbstractParser<LobbyHomeClassInfoListReq>() {
      @java.lang.Override
      public LobbyHomeClassInfoListReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LobbyHomeClassInfoListReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LobbyHomeClassInfoListReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.classlink.websocket.api.lobby.domain.param.proto.LobbyHomeClassInfoListReqProto.LobbyHomeClassInfoListReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_LobbyHomeClassInfoListReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_LobbyHomeClassInfoListReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037LobbyHomeClassInfoListReq.proto\022\tClass" +
      "link\"f\n\031LobbyHomeClassInfoListReq\022\017\n\007Ins" +
      "Code\030\001 \001(\t\022\024\n\014IdentityType\030\002 \001(\t\022\021\n\tStar" +
      "tDate\030\003 \001(\t\022\017\n\007EndDate\030\004 \001(\tBV\n4com.clas" +
      "slink.websocket.api.lobby.domain.param.p" +
      "rotoB\036LobbyHomeClassInfoListReqProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_LobbyHomeClassInfoListReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_LobbyHomeClassInfoListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_LobbyHomeClassInfoListReq_descriptor,
        new java.lang.String[] { "InsCode", "IdentityType", "StartDate", "EndDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
