// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CWExamQuizActivateReq.proto

package com.classlink.websocket.api.cw.domain.param.proto;

public final class CWExamQuizActivateReqProto {
  private CWExamQuizActivateReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CWExamQuizActivateReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Classlink.CWExamQuizActivateReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string DataTableType = 1;</code>
     * @return The dataTableType.
     */
    String getDataTableType();
    /**
     * <code>string DataTableType = 1;</code>
     * @return The bytes for dataTableType.
     */
    com.google.protobuf.ByteString
        getDataTableTypeBytes();

    /**
     * <code>int32 QuizSetIdx = 2;</code>
     * @return The quizSetIdx.
     */
    int getQuizSetIdx();

    /**
     * <code>int32 QuestionCount = 3;</code>
     * @return The questionCount.
     */
    int getQuestionCount();

    /**
     * <code>int32 LimitTime = 4;</code>
     * @return The limitTime.
     */
    int getLimitTime();

    /**
     * <code>bool IsShowCorrectAnswer = 5;</code>
     * @return The isShowCorrectAnswer.
     */
    boolean getIsShowCorrectAnswer();
  }
  /**
   * Protobuf type {@code Classlink.CWExamQuizActivateReq}
   */
  public static final class CWExamQuizActivateReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Classlink.CWExamQuizActivateReq)
      CWExamQuizActivateReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CWExamQuizActivateReq.newBuilder() to construct.
    private CWExamQuizActivateReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CWExamQuizActivateReq() {
      dataTableType_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CWExamQuizActivateReq();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CWExamQuizActivateReqProto.internal_static_Classlink_CWExamQuizActivateReq_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CWExamQuizActivateReqProto.internal_static_Classlink_CWExamQuizActivateReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CWExamQuizActivateReq.class, Builder.class);
    }

    public static final int DATATABLETYPE_FIELD_NUMBER = 1;
    private volatile Object dataTableType_;
    /**
     * <code>string DataTableType = 1;</code>
     * @return The dataTableType.
     */
    @Override
    public String getDataTableType() {
      Object ref = dataTableType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataTableType_ = s;
        return s;
      }
    }
    /**
     * <code>string DataTableType = 1;</code>
     * @return The bytes for dataTableType.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataTableTypeBytes() {
      Object ref = dataTableType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataTableType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUIZSETIDX_FIELD_NUMBER = 2;
    private int quizSetIdx_;
    /**
     * <code>int32 QuizSetIdx = 2;</code>
     * @return The quizSetIdx.
     */
    @Override
    public int getQuizSetIdx() {
      return quizSetIdx_;
    }

    public static final int QUESTIONCOUNT_FIELD_NUMBER = 3;
    private int questionCount_;
    /**
     * <code>int32 QuestionCount = 3;</code>
     * @return The questionCount.
     */
    @Override
    public int getQuestionCount() {
      return questionCount_;
    }

    public static final int LIMITTIME_FIELD_NUMBER = 4;
    private int limitTime_;
    /**
     * <code>int32 LimitTime = 4;</code>
     * @return The limitTime.
     */
    @Override
    public int getLimitTime() {
      return limitTime_;
    }

    public static final int ISSHOWCORRECTANSWER_FIELD_NUMBER = 5;
    private boolean isShowCorrectAnswer_;
    /**
     * <code>bool IsShowCorrectAnswer = 5;</code>
     * @return The isShowCorrectAnswer.
     */
    @Override
    public boolean getIsShowCorrectAnswer() {
      return isShowCorrectAnswer_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataTableType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataTableType_);
      }
      if (quizSetIdx_ != 0) {
        output.writeInt32(2, quizSetIdx_);
      }
      if (questionCount_ != 0) {
        output.writeInt32(3, questionCount_);
      }
      if (limitTime_ != 0) {
        output.writeInt32(4, limitTime_);
      }
      if (isShowCorrectAnswer_ != false) {
        output.writeBool(5, isShowCorrectAnswer_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dataTableType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataTableType_);
      }
      if (quizSetIdx_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, quizSetIdx_);
      }
      if (questionCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, questionCount_);
      }
      if (limitTime_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, limitTime_);
      }
      if (isShowCorrectAnswer_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isShowCorrectAnswer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CWExamQuizActivateReq)) {
        return super.equals(obj);
      }
      CWExamQuizActivateReq other = (CWExamQuizActivateReq) obj;

      if (!getDataTableType()
          .equals(other.getDataTableType())) return false;
      if (getQuizSetIdx()
          != other.getQuizSetIdx()) return false;
      if (getQuestionCount()
          != other.getQuestionCount()) return false;
      if (getLimitTime()
          != other.getLimitTime()) return false;
      if (getIsShowCorrectAnswer()
          != other.getIsShowCorrectAnswer()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATABLETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDataTableType().hashCode();
      hash = (37 * hash) + QUIZSETIDX_FIELD_NUMBER;
      hash = (53 * hash) + getQuizSetIdx();
      hash = (37 * hash) + QUESTIONCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getQuestionCount();
      hash = (37 * hash) + LIMITTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLimitTime();
      hash = (37 * hash) + ISSHOWCORRECTANSWER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsShowCorrectAnswer());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CWExamQuizActivateReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CWExamQuizActivateReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CWExamQuizActivateReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CWExamQuizActivateReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CWExamQuizActivateReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CWExamQuizActivateReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CWExamQuizActivateReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CWExamQuizActivateReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CWExamQuizActivateReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CWExamQuizActivateReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CWExamQuizActivateReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CWExamQuizActivateReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CWExamQuizActivateReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Classlink.CWExamQuizActivateReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Classlink.CWExamQuizActivateReq)
        CWExamQuizActivateReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CWExamQuizActivateReqProto.internal_static_Classlink_CWExamQuizActivateReq_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CWExamQuizActivateReqProto.internal_static_Classlink_CWExamQuizActivateReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CWExamQuizActivateReq.class, Builder.class);
      }

      // Construct using com.classlink.websocket.api.cw.domain.param.proto.CWExamQuizActivateReqProto.CWExamQuizActivateReq.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        dataTableType_ = "";

        quizSetIdx_ = 0;

        questionCount_ = 0;

        limitTime_ = 0;

        isShowCorrectAnswer_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CWExamQuizActivateReqProto.internal_static_Classlink_CWExamQuizActivateReq_descriptor;
      }

      @Override
      public CWExamQuizActivateReq getDefaultInstanceForType() {
        return CWExamQuizActivateReq.getDefaultInstance();
      }

      @Override
      public CWExamQuizActivateReq build() {
        CWExamQuizActivateReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CWExamQuizActivateReq buildPartial() {
        CWExamQuizActivateReq result = new CWExamQuizActivateReq(this);
        result.dataTableType_ = dataTableType_;
        result.quizSetIdx_ = quizSetIdx_;
        result.questionCount_ = questionCount_;
        result.limitTime_ = limitTime_;
        result.isShowCorrectAnswer_ = isShowCorrectAnswer_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CWExamQuizActivateReq) {
          return mergeFrom((CWExamQuizActivateReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CWExamQuizActivateReq other) {
        if (other == CWExamQuizActivateReq.getDefaultInstance()) return this;
        if (!other.getDataTableType().isEmpty()) {
          dataTableType_ = other.dataTableType_;
          onChanged();
        }
        if (other.getQuizSetIdx() != 0) {
          setQuizSetIdx(other.getQuizSetIdx());
        }
        if (other.getQuestionCount() != 0) {
          setQuestionCount(other.getQuestionCount());
        }
        if (other.getLimitTime() != 0) {
          setLimitTime(other.getLimitTime());
        }
        if (other.getIsShowCorrectAnswer() != false) {
          setIsShowCorrectAnswer(other.getIsShowCorrectAnswer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                dataTableType_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                quizSetIdx_ = input.readInt32();

                break;
              } // case 16
              case 24: {
                questionCount_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                limitTime_ = input.readInt32();

                break;
              } // case 32
              case 40: {
                isShowCorrectAnswer_ = input.readBool();

                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private Object dataTableType_ = "";
      /**
       * <code>string DataTableType = 1;</code>
       * @return The dataTableType.
       */
      public String getDataTableType() {
        Object ref = dataTableType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dataTableType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string DataTableType = 1;</code>
       * @return The bytes for dataTableType.
       */
      public com.google.protobuf.ByteString
          getDataTableTypeBytes() {
        Object ref = dataTableType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataTableType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string DataTableType = 1;</code>
       * @param value The dataTableType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTableType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataTableType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string DataTableType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataTableType() {
        
        dataTableType_ = getDefaultInstance().getDataTableType();
        onChanged();
        return this;
      }
      /**
       * <code>string DataTableType = 1;</code>
       * @param value The bytes for dataTableType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTableTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataTableType_ = value;
        onChanged();
        return this;
      }

      private int quizSetIdx_ ;
      /**
       * <code>int32 QuizSetIdx = 2;</code>
       * @return The quizSetIdx.
       */
      @Override
      public int getQuizSetIdx() {
        return quizSetIdx_;
      }
      /**
       * <code>int32 QuizSetIdx = 2;</code>
       * @param value The quizSetIdx to set.
       * @return This builder for chaining.
       */
      public Builder setQuizSetIdx(int value) {
        
        quizSetIdx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 QuizSetIdx = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuizSetIdx() {
        
        quizSetIdx_ = 0;
        onChanged();
        return this;
      }

      private int questionCount_ ;
      /**
       * <code>int32 QuestionCount = 3;</code>
       * @return The questionCount.
       */
      @Override
      public int getQuestionCount() {
        return questionCount_;
      }
      /**
       * <code>int32 QuestionCount = 3;</code>
       * @param value The questionCount to set.
       * @return This builder for chaining.
       */
      public Builder setQuestionCount(int value) {
        
        questionCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 QuestionCount = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuestionCount() {
        
        questionCount_ = 0;
        onChanged();
        return this;
      }

      private int limitTime_ ;
      /**
       * <code>int32 LimitTime = 4;</code>
       * @return The limitTime.
       */
      @Override
      public int getLimitTime() {
        return limitTime_;
      }
      /**
       * <code>int32 LimitTime = 4;</code>
       * @param value The limitTime to set.
       * @return This builder for chaining.
       */
      public Builder setLimitTime(int value) {
        
        limitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 LimitTime = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimitTime() {
        
        limitTime_ = 0;
        onChanged();
        return this;
      }

      private boolean isShowCorrectAnswer_ ;
      /**
       * <code>bool IsShowCorrectAnswer = 5;</code>
       * @return The isShowCorrectAnswer.
       */
      @Override
      public boolean getIsShowCorrectAnswer() {
        return isShowCorrectAnswer_;
      }
      /**
       * <code>bool IsShowCorrectAnswer = 5;</code>
       * @param value The isShowCorrectAnswer to set.
       * @return This builder for chaining.
       */
      public Builder setIsShowCorrectAnswer(boolean value) {
        
        isShowCorrectAnswer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool IsShowCorrectAnswer = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsShowCorrectAnswer() {
        
        isShowCorrectAnswer_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Classlink.CWExamQuizActivateReq)
    }

    // @@protoc_insertion_point(class_scope:Classlink.CWExamQuizActivateReq)
    private static final CWExamQuizActivateReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CWExamQuizActivateReq();
    }

    public static CWExamQuizActivateReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CWExamQuizActivateReq>
        PARSER = new com.google.protobuf.AbstractParser<CWExamQuizActivateReq>() {
      @Override
      public CWExamQuizActivateReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CWExamQuizActivateReq> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CWExamQuizActivateReq> getParserForType() {
      return PARSER;
    }

    @Override
    public CWExamQuizActivateReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Classlink_CWExamQuizActivateReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Classlink_CWExamQuizActivateReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033CWExamQuizActivateReq.proto\022\tClasslink" +
      "\"\211\001\n\025CWExamQuizActivateReq\022\025\n\rDataTableT" +
      "ype\030\001 \001(\t\022\022\n\nQuizSetIdx\030\002 \001(\005\022\025\n\rQuestio" +
      "nCount\030\003 \001(\005\022\021\n\tLimitTime\030\004 \001(\005\022\033\n\023IsSho" +
      "wCorrectAnswer\030\005 \001(\010BO\n1com.classlink.we" +
      "bsocket.api.cw.domain.param.protoB\032CWExa" +
      "mQuizActivateReqProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Classlink_CWExamQuizActivateReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Classlink_CWExamQuizActivateReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Classlink_CWExamQuizActivateReq_descriptor,
        new String[] { "DataTableType", "QuizSetIdx", "QuestionCount", "LimitTime", "IsShowCorrectAnswer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
