package com.classlink.websocket.api.common;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum OpCode {
	
	DEFAULT(0), IDENTITY_CREATE(100), IDENTITY_LIST(101), 
	AVATAR_CREATE(102), AVATAR_INFO(103), AVATAR_CHANGE(104),
	INSTITUTION_INFO(105), INSTITUTION_ENROLLMENT_REQUEST_CREATE(106),
	INSTITUTION_ENROLLMENT_REQUEST_LIST(107),INSTITUTION_ENROLLMENT_REQUEST_VIEW_STATUS_CHANGE(108),
	INSTITUTION_ENROLLMENT_REQUESTER_INFO(109),INSTITUTION_ENROLLMENT_REQUEST_STATUS_CHANGE(110),
	INSTITUTION_MY_LIST(120);

	private final int code;

}
