package com.classlink.websocket.api.common;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum OpCode {
	
	DEFAULT(0), IDENTITY_CREATE(100), IDENTITY_LIST(101), 
	AVATAR_CREATE(102), AVATAR_INFO(103), AVATAR_CHANGE(104),
	INSTITUTION_INFO(105), INSTITUTION_ENROLLMENT_REQUEST_CREATE(106),
	INSTITUTION_ENROLLMENT_REQUEST_LIST(107),INSTITUTION_ENROLLMENT_REQUEST_VIEW_STATUS_CHANGE(108),
	INSTITUTION_ENROLLMENT_REQUESTER_INFO(109),INSTITUTION_ENROLLMENT_REQUEST_STATUS_CHANGE(110),
	LOGIN_INSTITUTE_REGISTRATION_CHANGE(112), LOGIN_IDENTITY_REGISTRATION_CHANGE(113),
	INSTITUTION_MY_LIST(117),
	SYS_WORLD_SET_INFO(120), SYS_WORLD_OBJ_SET_CREATE_LIST(127), SYS_WORLD_OBJ_SET_INIT_LIST(128);

	private final int code;

}
